/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : ADC_BAL.c
**     Project     : 39_16_52_IN1UP
**     Processor   : MCF52233CAF60
**     Component   : ADC
**     Version     : Component 01.699, Driver 01.05, CPU db: 3.00.000
**     Compiler    : CodeWarrior MCF C Compiler
**     Date/Time   : 2022-09-13, 17:04, # CodeGen: 0
**     Abstract    :
**         This device "ADC" implements an A/D converter,
**         its control methods and interrupt/event handling procedure.
**     Settings    :
**          Component name                                 : ADC_BAL
**          A/D converter                                  : ADC
**          Sharing                                        : Disabled
**          Interrupt service/event                        : Enabled
**            A/D interrupt                                : INT_ADC_ADCA
**            A/D interrupt priority                       : level 1, priority within level 5
**            Interrupt                                    : INT_ADC_ADCINT
**            Interrupt priority                           : level 1, priority within level 4
**          A/D channels                                   : 2
**            Channel0                                     : 
**              A/D channel (pin)                          : AN3_PAN3
**              A/D channel (pin) signal                   : Balance_Voltage
**              Mode select                                : Single Ended
**            Channel1                                     : 
**              A/D channel (pin)                          : AN5_PAN5
**              A/D channel (pin) signal                   : Driver_Volts
**              Mode select                                : Single Ended
**          Queue                                          : Enabled
**            Mode                                         : Sequential
**            A/D samples                                  : 8
**              Sample0                                    : Enabled
**                Channel                                  : 0
**                High limit                               : 32760
**                Low limit                                : 0
**                Offset                                   : 0
**                Zero crossing                            : Disabled
**              Sample1                                    : Enabled
**                Channel                                  : 1
**                High limit                               : 32760
**                Low limit                                : 0
**                Offset                                   : 0
**                Zero crossing                            : Disabled
**              Sample2                                    : Disabled
**              Sample3                                    : Disabled
**              Sample4                                    : Disabled
**              Sample5                                    : Disabled
**              Sample6                                    : Disabled
**              Sample7                                    : Disabled
**          A/D resolution                                 : 12 bits
**          Conversion time                                : 18.133333 µs
**          External trigger                               : Disabled
**          Internal trigger                               : Disabled
**          Volt. ref. recovery time                       : 100
**          Power up delay                                 : 61
**          Power savings mode                             : Disabled
**          Auto standby                                   : Disabled
**          Volt. ref. source                              : controlled by this component for both converter
**            High volt. ref. source                       : internal
**            Low volt. ref. source                        : internal
**          Number of conversions                          : 8
**          Initialization                                 : 
**            Enabled in init. code                        : yes
**            Events enabled in init.                      : yes
**          CPU clock/speed selection                      : 
**            High speed mode                              : This component enabled
**            Low speed mode                               : This component disabled
**            Slow speed mode                              : This component disabled
**          High input limit                               : 1
**          Low input limit                                : 0
**          Get value directly                             : yes
**          Wait for result                                : yes
**     Contents    :
**         Enable     - byte ADC_BAL_Enable(void);
**         Disable    - byte ADC_BAL_Disable(void);
**         Start      - byte ADC_BAL_Start(void);
**         Measure    - byte ADC_BAL_Measure(bool WaitForResult);
**         GetValue16 - byte ADC_BAL_GetValue16(word *Values);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file ADC_BAL.c
** @version 01.05
** @brief
**         This device "ADC" implements an A/D converter,
**         its control methods and interrupt/event handling procedure.
*/         
/*!
**  @addtogroup ADC_BAL_module ADC_BAL module documentation
**  @{
*/         

/* MODULE ADC_BAL. */

#include "ADC_BAL.h"

#define IDLE            0              /* IDLE state           */
#define MEASURE         1              /* MESURE state         */
#define CONTINUOUS      2              /* CONTINUOUS state     */
#define SINGLE          3              /* SINGLE state         */

/*lint -esym(765,ADC_BAL_EnUser) Disable MISRA rule (23) checking for symbols (ADC_BAL_EnUser). */
bool ADC_BAL_EnUser;                   /* Enable/Disable device */
static bool OutFlg;                    /* Measurement finish flag */
/*lint -esym(765,ADC_BAL_ModeFlg) Disable MISRA rule (23) checking for symbols (ADC_BAL_ModeFlg). */
volatile byte ADC_BAL_ModeFlg;         /* Current state of device */
static byte SumCnt;                    /* Number of conversions */
static dword ADC_BAL_SumV[2];          /* Sum of measured values */
static dword ADC_BAL_OutV[2];          /* Sum of measured values */

/*
** ===================================================================
**     Method      :  ClrSumV (component ADC)
**
**     Description :
**         Clear values for cumulation of measured results.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void ClrSumV(void)
{
  ADC_BAL_SumV[0] = 0;                 /* Set variable for storing measured values to 0 */
  ADC_BAL_SumV[1] = 0;                 /* Set variable for storing measured values to 0 */
}

/*
** ===================================================================
**     Method      :  ADC_BAL_InterruptCC (component ADC)
**
**     Description :
**         The method services the conversion complete interrupt of the 
**         selected peripheral(s) and eventually invokes the components 
**         event(s).
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
__declspec(interrupt) void ADC_BAL_InterruptCC(void)
{
  setReg16Bits(ADSTAT,0x0800);         /* Clear EOSI flag */
  ADC_BAL_SumV[0] += getReg16(ADRSLT0); /* Save measured values to the output buffer */
  ADC_BAL_SumV[1] += getReg16(ADRSLT1); /* Save measured values to the output buffer */
  SumCnt++;
  if ( SumCnt == 8 ) {
    OutFlg = TRUE;                     /* Measured values are available */
    ADC_BAL_OutV[0] = ADC_BAL_SumV[0]; /* Save measured values to the output buffer */
    ADC_BAL_OutV[1] = ADC_BAL_SumV[1]; /* Save measured values to the output buffer */
    if (ADC_BAL_ModeFlg == CONTINUOUS) { /* Running in continuous mode? */
      ClrSumV();                       /* Clear measured values */
      SumCnt = 0;                      /* Clear the number of conversions */
      setReg16Bit(CTRL1,START0);       /* Launching of conversion */
    }
    else {
      ADC_BAL_ModeFlg = IDLE;          /* Set the component to the idle mode */
    }
  }
  else {
    setReg16Bit(CTRL1,START0);         /* Launching of conversion */
  }
}

/*
** ===================================================================
**     Method      :  HWEnDi (component ADC)
**
**     Description :
**         Enables or disables the peripheral(s) associated with the 
**         component. The method is called automatically as a part of 
**         Enable, Disable and Init methods and several internal methods.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void HWEnDi(void)
{
  volatile word i;

  if (ADC_BAL_EnUser) {                /* Enable device? */
    if (testReg16Bits(POWER,(POWER_PSTS0_BITMASK|POWER_PSTS1_BITMASK|POWER_PSTS2_BITMASK))) { /* Is device enabled? */
      /* POWER: ASB=0,??=0,??=0,PSTS2=0,PSTS1=0,PSTS0=0,PUDELAY=0x3D,APD=0,PD2=0,PD1=0,PD0=0 */
      setReg16(POWER,0x03D0);          /* Enable device */
      for (i=0;i<0x64;i++) {}          /* Recovery time of voltage reference */
      while (POWER&((POWER_PSTS0_BITMASK|POWER_PSTS1_BITMASK|POWER_PSTS2_BITMASK))) {} /* Wait for device powered up */
    }
    if (ADC_BAL_ModeFlg) {             /* Launch measurement? */
      SumCnt = 0;                      /* Clear the number of conversions */
      OutFlg = FALSE;                  /* Measured values are available */
      ClrSumV();                       /* Clear measured values */
      clrReg16Bit(CTRL1,STOP0);        /* Normal operation mode */
      setReg16Bit(CTRL1,START0);       /* Launching of conversion */
    }
    else {
      setReg16Bit(CTRL1,STOP0);        /* Stop command issued */
    }
  }
  else {
    setReg16Bit(CTRL1,STOP0);          /* Stop command issued */
    /* POWER: ASB=0,??=0,??=0,PSTS2=0,PSTS1=0,PSTS0=0,PUDELAY=0x3D,APD=0,PD2=1,PD1=1,PD0=1 */
    setReg16(POWER,0x03D7);            /* Disable device */
  }
}

/*
** ===================================================================
**     Method      :  ADC_BAL_Enable (component ADC)
*/
/*!
**     @brief
**         Enables A/D converter component. [Events] may be generated
**         ([DisableEvent]/[EnableEvent]). If possible, this method
**         switches on A/D converter device, voltage reference, etc.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
*/
/* ===================================================================*/
byte ADC_BAL_Enable(void)
{
  if (ADC_BAL_EnUser) {                /* Is the device enabled by user? */
    return ERR_OK;                     /* If yes then set the flag "device enabled" */
  }
  ADC_BAL_EnUser = TRUE;               /* Set the flag "device enabled" */
  HWEnDi();                            /* Enable the device */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  ADC_BAL_Disable (component ADC)
*/
/*!
**     @brief
**         Disables A/D converter component. No [events] will be
**         generated. If possible, this method switches off A/D
**         converter device, voltage reference, etc.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
*/
/* ===================================================================*/
byte ADC_BAL_Disable(void)
{
  if (!ADC_BAL_EnUser) {               /* Is the device disabled by user? */
    return ERR_OK;                     /* If yes then OK */
  }
  ADC_BAL_EnUser = FALSE;              /* If yes then set the flag "device disabled" */
  HWEnDi();                            /* Enable the device */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  ADC_BAL_Start (component ADC)
*/
/*!
**     @brief
**         This method starts continuous conversion on all channels
**         that are set in the component inspector. When each
**         measurement on all channels has finished the [OnEnd ] event
**         may be invoked. This method is not available if the
**         [interrupt service] is disabled and the device doesn't
**         support the continuous mode. Note: If time of measurement is
**         too short and the instruction clock is too slow then the
**         conversion complete interrupt and its handler may cause a
**         system overflow.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED - Device is disabled
**                           ERR_BUSY - A conversion is already running
*/
/* ===================================================================*/
byte ADC_BAL_Start(void)
{
  if (!ADC_BAL_EnUser) {               /* Is the device disabled by user? */
    return ERR_DISABLED;               /* If yes then error */
  }
  if (ADC_BAL_ModeFlg != IDLE) {       /* Is the device in running mode? */
    return ERR_BUSY;                   /* If yes then error */
  }
  ADC_BAL_ModeFlg = CONTINUOUS;        /* Set state of device to the continuous mode */
  HWEnDi();                            /* Enable the device */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  ADC_BAL_Measure (component ADC)
*/
/*!
**     @brief
**         This method performs one measurement on all channels that
**         are set in the component inspector. (Note: If the [number of
**         conversions] is more than one the conversion of A/D channels
**         is performed specified number of times.)
**     @param
**         WaitForResult   - Wait for a result of a
**                           conversion. If [interrupt service] is
**                           disabled, A/D peripheral doesn't support
**                           measuring all channels at once or Autoscan
**                           mode property isn't enabled and at the same
**                           time the [number of channels] is greater
**                           than 1, then the WaitForResult parameter is
**                           ignored and the method waits for each
**                           result every time. If the [interrupt
**                           service] is disabled and a [number of
**                           conversions] is greater than 1, the
**                           parameter is ignored and the method also
**                           waits for each result every time.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED - Device is disabled
**                           ERR_BUSY - A conversion is already running
*/
/* ===================================================================*/
byte ADC_BAL_Measure(bool WaitForResult)
{
  if (!ADC_BAL_EnUser) {               /* Is the device disabled by user? */
    return ERR_DISABLED;               /* If yes then error */
  }
  if (ADC_BAL_ModeFlg != IDLE) {       /* Is the device in running mode? */
    return ERR_BUSY;                   /* If yes then error */
  }
  ADC_BAL_ModeFlg = MEASURE;           /* Set state of device to the measure mode */
  HWEnDi();                            /* Enable the device */
  if (WaitForResult)                   /* Is WaitForResult TRUE? */
    while (ADC_BAL_ModeFlg == MEASURE) {} /* If yes then wait for end of measurement */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  ADC_BAL_GetValue16 (component ADC)
*/
/*!
**     @brief
**         This method returns the last measured values of all channels.
**         Compared with [GetValue] method this method returns more
**         accurate result if the [number of conversions] is greater
**         than 1 and [AD resolution] is less than 16 bits. In addition,
**         the user code dependency on [AD resolution] is eliminated.
**     @param
**         Values          - Pointer to the array that contains
**                           the measured data.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_NOTAVAIL - Requested value not
**                           available
**                           ERR_OVERRUN - External trigger overrun flag
**                           was detected after the last value(s) was
**                           obtained (for example by GetValue). This
**                           error may not be supported on some CPUs
**                           (see generated code).
*/
/* ===================================================================*/
byte ADC_BAL_GetValue16(word *Values)
{
  if (!OutFlg) {                       /* Is measured value(s) available? */
    return ERR_NOTAVAIL;               /* If no then error */
  }
  *Values++ = (word)((((word)(ADC_BAL_OutV[0] / 8)) + 0x00) << 1); /* Store value from output to user buffer */
  *Values = (word)((((word)(ADC_BAL_OutV[1] / 8)) + 0x00) << 1); /* Store value from output to user buffer */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  ADC_BAL_Init (component ADC)
**
**     Description :
**         Initializes the associated peripheral(s) and the components 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void ADC_BAL_Init(void)
{
  ADC_BAL_EnUser = TRUE;               /* Enable device */
  OutFlg = FALSE;                      /* No measured value */
  ADC_BAL_ModeFlg = IDLE;              /* Device isn't running */
  /* CTRL1: ??=0,STOP0=1,START0=0,SYNC0=0,EOSIE0=1,ZCIE=0,LLMTIE=0,HLMTIE=0,CHNCFG=0,??=0,SMODE=0 */
  setReg16(CTRL1,0x4800);              /* Set control register 1 */
  /* CAL: SEL_VREFH=0,SEL_VREFL=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg16(CAL,0x00);                  /* Set calibration register */
  /* ADOFS0: ??=0,OFFSET=0,??=0,??=0,??=0 */
  setReg16(ADOFS0,0x00);               /* Set offset reg. 0 */
  /* ADOFS1: ??=0,OFFSET=0,??=0,??=0,??=0 */
  setReg16(ADOFS1,0x00);               /* Set offset reg. 1 */
  /* ADHLMT0: ??=0,HLMT=0x0FFF,??=0,??=0,??=0 */
  setReg16(ADHLMT0,0x7FF8);            /* Set high limit reg. 0 */
  /* ADHLMT1: ??=0,HLMT=0x0FFF,??=0,??=0,??=0 */
  setReg16(ADHLMT1,0x7FF8);            /* Set high limit reg. 1 */
  /* ADLLMT0: ??=0,LLMT=0,??=0,??=0,??=0 */
  setReg16(ADLLMT0,0x00);              /* Set low limit reg. 0 */
  /* ADLLMT1: ??=0,LLMT=0,??=0,??=0,??=0 */
  setReg16(ADLLMT1,0x00);              /* Set low limit reg. 1 */
  /* ADZCSTAT: ??=1,??=1,??=1,??=1,??=1,??=1,??=1,??=1,ZCS7=1,ZCS6=1,ZCS5=1,ZCS4=1,ZCS3=1,ZCS2=1,ZCS1=1,ZCS0=1 */
  setReg16(ADZCSTAT,0xFFFF);           /* Clear zero crossing status flags */
  /* ADLSTAT: HLS7=1,HLS6=1,HLS5=1,HLS4=1,HLS3=1,HLS2=1,HLS1=1,HLS0=1,LLS7=1,LLS6=1,LLS5=1,LLS4=1,LLS3=1,LLS2=1,LLS1=1,LLS0=1 */
  setReg16(ADLSTAT,0xFFFF);            /* Clear high and low limit status */
  /* ADSTAT: CIP0=0,CIP1=0,??=0,EOSI1=0,EOSI0=1,ZCI=0,LLMTI=0,HLMTI=0,RDY7=0,RDY6=0,RDY5=0,RDY4=0,RDY3=0,RDY2=0,RDY1=0,RDY0=0 */
  setReg16(ADSTAT,0x0800);             /* Clear EOSI flag */
  /* ADSDIS: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,DS7=1,DS6=1,DS5=1,DS4=1,DS3=1,DS2=1,DS1=0,DS0=0 */
  setReg16(ADSDIS,0xFC);               /* Enable/disable of samples */
  /* ADLST1: ??=0,SAMPLE3=0,??=0,SAMPLE2=0,??=0,SAMPLE1=5,??=0,SAMPLE0=3 */
  setReg16(ADLST1,0x53);               /* Set ADC channel list reg. */
  /* ADZCC: ZCE7=0,ZCE6=0,ZCE5=0,ZCE4=0,ZCE3=0,ZCE2=0,ZCE1=0,ZCE0=0 */
  setReg16(ADZCC,0x00);                /* Set zero crossing control reg. */
  /* CTRL2: ??=0,STOP1=0,START1=0,SYNC1=0,EOSIE1=0,??=0,??=0,??=0,??=0,??=0,SIMULT=1,DIV=0x15 */
  setReg16(CTRL2,0x35);                /* Set prescaler */
  HWEnDi();                            /* Enable/disable device according to the status flags */
}



/* END ADC_BAL. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale MCF series of microcontrollers.
**
** ###################################################################
*/
