/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : IOUPserial.h
**     Project     : 39_16_52_IN1UP
**     Processor   : MCF52233CAF60
**     Component   : AsynchroSerial
**     Version     : Component 02.611, Driver 01.02, CPU db: 3.00.000
**     Compiler    : CodeWarrior MCF C Compiler
**     Date/Time   : 2022-09-13, 17:04, # CodeGen: 0
**     Abstract    :
**         This component "AsynchroSerial" implements an asynchronous serial
**         communication. The component supports different settings of
**         parity, word width, stop-bit and communication speed,
**         user can select interrupt or polling handler.
**         Communication speed can be changed also in runtime.
**         The component requires one on-chip asynchronous serial channel.
**     Settings    :
**         Serial channel              : UART0
**
**         Protocol
**             Init baud rate          : 19200baud
**             Width                   : 8 bits
**             Stop bits               : 1.000
**             Parity                  : none
**             Breaks                  : Disabled
**             Input buffer size       : 30
**             Output buffer size      : 100
**
**         Registers
**             Input buffer            : URB0      [0x020C]
**             Output buffer           : UTB0      [0x020C]
**             Control register        : UMR10     [0x0200]
**             Mode register           : UMR20     [0x0200]
**             Baud setting reg.       : UCSR0     [0x0204]
**
**         Input interrupt
**             Vector name             : INT_UART0
**             Priority                : 430
**
**         Output interrupt
**             Vector name             : INT_UART0
**             Priority                : 430
**
**         Used pins:
**         ----------------------------------------------------------
**           Function | On package           |    Name
**         ----------------------------------------------------------
**            Input   |     21               |  URXD0_FEC_RXD0_PUA1
**            Output  |     22               |  UTXD0_FEC_CRS_PUA0
**         ----------------------------------------------------------
**
**
**
**     Contents    :
**         EnableEvent     - byte IOUPserial_EnableEvent(void);
**         DisableEvent    - byte IOUPserial_DisableEvent(void);
**         RecvChar        - byte IOUPserial_RecvChar(IOUPserial_TComData *Chr);
**         SendChar        - byte IOUPserial_SendChar(IOUPserial_TComData Chr);
**         RecvBlock       - byte IOUPserial_RecvBlock(IOUPserial_TComData *Ptr, word Size, word *Rcv);
**         SendBlock       - byte IOUPserial_SendBlock(IOUPserial_TComData *Ptr, word Size, word *Snd);
**         ClearRxBuf      - byte IOUPserial_ClearRxBuf(void);
**         ClearTxBuf      - byte IOUPserial_ClearTxBuf(void);
**         CharsInRxBuf    - byte IOUPserial_CharsInRxBuf(word *Chr);
**         GetCharsInRxBuf - word IOUPserial_GetCharsInRxBuf(void);
**         CharsInTxBuf    - byte IOUPserial_CharsInTxBuf(word *Chr);
**         GetCharsInTxBuf - word IOUPserial_GetCharsInTxBuf(void);
**         GetError        - byte IOUPserial_GetError(IOUPserial_TError *Err);
**         TurnTxOn        - void IOUPserial_TurnTxOn(void);
**         TurnTxOff       - void IOUPserial_TurnTxOff(void);
**         TurnRxOn        - void IOUPserial_TurnRxOn(void);
**         TurnRxOff       - void IOUPserial_TurnRxOff(void);
**         GetTxComplete   - bool IOUPserial_GetTxComplete(void);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file IOUPserial.h
** @version 01.02
** @brief
**         This component "AsynchroSerial" implements an asynchronous serial
**         communication. The component supports different settings of
**         parity, word width, stop-bit and communication speed,
**         user can select interrupt or polling handler.
**         Communication speed can be changed also in runtime.
**         The component requires one on-chip asynchronous serial channel.
*/         
/*!
**  @addtogroup IOUPserial_module IOUPserial module documentation
**  @{
*/         

#ifndef __IOUPserial
#define __IOUPserial

/* MODULE IOUPserial. */

#include "Cpu.h"



#ifndef __BWUserType_IOUPserial_TError
#define __BWUserType_IOUPserial_TError
  typedef union {
    byte err;
    struct {
      bool OverRun  : 1;               /* Overrun error flag */
      bool Framing  : 1;               /* Framing error flag */
      bool Parity   : 1;               /* Parity error flag */
      bool RxBufOvf : 1;               /* Rx buffer full error flag */
      bool Noise    : 1;               /* Noise error flag */
      bool Break    : 1;               /* Break detect */
      bool LINSync  : 1;               /* LIN synchronization error */
      bool BitError  : 1;              /* Bit error flag - mismatch to the expected value happened. */
    } errName;
  } IOUPserial_TError;                 /* Error flags. For languages which don't support bit access is byte access only to error flags possible. */
#endif

#ifndef __BWUserType_IOUPserial_TComData
#define __BWUserType_IOUPserial_TComData
  typedef byte IOUPserial_TComData;    /* User type for communication. Size of this type depends on the communication data witdh */
#endif

#define IOUPserial_INP_BUF_SIZE  0x1E  /* Length of the RX buffer */

#define IOUPserial_OUT_BUF_SIZE  0x64  /* Length of the TX buffer */


extern volatile bool IOUPserial_EnEvent; /* Enable/Disable events */

extern volatile word IOUPserial_OutLen; /* Length of output bufer's content */
extern volatile word IOUPserial_InpLen; /* Length of input buffer's content */

byte IOUPserial_EnableEvent(void);
/*
** ===================================================================
**     Method      :  IOUPserial_EnableEvent (component AsynchroSerial)
**     Description :
**         Enables the events. This method is available if the
**         interrupt service/event property is enabled and at least one
**         event is enabled.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/

byte IOUPserial_DisableEvent(void);
/*
** ===================================================================
**     Method      :  IOUPserial_DisableEvent (component AsynchroSerial)
**     Description :
**         Disables the events. This method is available if the
**         interrupt service/event property is enabled and at least one
**         event is enabled.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/

byte IOUPserial_RecvChar(IOUPserial_TComData *Chr);
/*
** ===================================================================
**     Method      :  IOUPserial_RecvChar (component AsynchroSerial)
**     Description :
**         If any data is received, this method returns one character,
**         otherwise it returns an error code (it does not wait for
**         data). This method is enabled only if the receiver property
**         is enabled.
**         [Note:] Because the preferred method to handle error and
**         break exception in the interrupt mode is to use events
**         <OnError> and <OnBreak> the return value ERR_RXEMPTY has
**         higher priority than other error codes. As a consequence the
**         information about an exception in interrupt mode is returned
**         only if there is a valid character ready to be read.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Chr             - Pointer to a received character
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_RXEMPTY - No data in receiver
**                           ERR_BREAK - Break character is detected
**                           (only when the <Interrupt service> property
**                           is disabled and the <Break signal> property
**                           is enabled)
**                           ERR_COMMON - common error occurred (the
**                           <GetError> method can be used for error
**                           specification)
** ===================================================================
*/

byte IOUPserial_SendChar(IOUPserial_TComData Chr);
/*
** ===================================================================
**     Method      :  IOUPserial_SendChar (component AsynchroSerial)
**     Description :
**         Sends one character to the channel. If the component is
**         temporarily disabled (Disable method) SendChar method only
**         stores data into an output buffer. In case of a zero output
**         buffer size, only one character can be stored. Enabling the
**         component (Enable method) starts the transmission of the
**         stored data. This method is available only if the
**         transmitter property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Chr             - Character to send
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_TXFULL - Transmitter is full
** ===================================================================
*/

byte IOUPserial_RecvBlock(IOUPserial_TComData *Ptr,word Size,word *Rcv);
/*
** ===================================================================
**     Method      :  IOUPserial_RecvBlock (component AsynchroSerial)
**     Description :
**         If any data is received, this method returns the block of
**         the data and its length (and incidental error), otherwise it
**         returns an error code (it does not wait for data).
**         This method is available only if non-zero length of the
**         input buffer is defined and the receiver property is enabled.
**         If less than requested number of characters is received only
**         the available data is copied from the receive buffer to the
**         user specified destination. The value ERR_EXEMPTY is
**         returned and the value of variable pointed by the Rcv
**         parameter is set to the number of received characters.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Ptr             - Pointer to the block of received data
**         Size            - Size of the block
**       * Rcv             - Pointer to real number of the received data
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_RXEMPTY - The receive buffer didn't
**                           contain the requested number of data. Only
**                           available data has been returned.
**                           ERR_COMMON - common error occurred (the
**                           GetError method can be used for error
**                           specification)
** ===================================================================
*/

byte IOUPserial_SendBlock(IOUPserial_TComData *Ptr,word Size,word *Snd);
/*
** ===================================================================
**     Method      :  IOUPserial_SendBlock (component AsynchroSerial)
**     Description :
**         Sends a block of characters to the channel.
**         This method is available only if non-zero length of the
**         output buffer is defined and the transmitter property is
**         enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Ptr             - Pointer to the block of data to send
**         Size            - Size of the block
**       * Snd             - Pointer to number of data that are sent
**                           (moved to buffer)
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_TXFULL - It was not possible to send
**                           requested number of bytes
** ===================================================================
*/

byte IOUPserial_ClearRxBuf(void);
/*
** ===================================================================
**     Method      :  IOUPserial_ClearRxBuf (component AsynchroSerial)
**     Description :
**         Clears the receive buffer.
**         This method is available only if non-zero length of the
**         input buffer is defined and the receiver property is enabled.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/

byte IOUPserial_ClearTxBuf(void);
/*
** ===================================================================
**     Method      :  IOUPserial_ClearTxBuf (component AsynchroSerial)
**     Description :
**         Clears the transmit buffer.
**         This method is available only if non-zero length of the
**         output buffer is defined and the receiver property is
**         enabled.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/

byte  IOUPserial_CharsInRxBuf(word *Chr);
/*
** ===================================================================
**     Method      :  IOUPserial_CharsInRxBuf (component AsynchroSerial)
**     Description :
**         Returns the number of characters in the input buffer. This
**         method is available only if the receiver property is enabled.
**         [deprecated method]
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Chr             - Pointer to the number of characters in the
**                           input buffer
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/

word IOUPserial_GetCharsInRxBuf(void);
/*
** ===================================================================
**     Method      :  IOUPserial_GetCharsInRxBuf (component AsynchroSerial)
**     Description :
**         Returns the number of characters in the input buffer. This
**         method is available only if the receiver property is enabled.
**     Parameters  : None
**     Returns     :
**         ---             - The number of characters in the input
**                           buffer.
** ===================================================================
*/

byte IOUPserial_CharsInTxBuf(word *Chr);
/*
** ===================================================================
**     Method      :  IOUPserial_CharsInTxBuf (component AsynchroSerial)
**     Description :
**         Returns the number of characters in the output buffer. This
**         method is available only if the transmitter property is
**         enabled.
**         [deprecated method]
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Chr             - Pointer to the number of characters in the
**                           output buffer
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/

word IOUPserial_GetCharsInTxBuf(void);
/*
** ===================================================================
**     Method      :  IOUPserial_GetCharsInTxBuf (component AsynchroSerial)
**     Description :
**         Returns the number of characters in the output buffer. This
**         method is available only if the transmitter property is
**         enabled.
**     Parameters  : None
**     Returns     :
**         ---             - The number of characters in the output
**                           buffer.
** ===================================================================
*/

byte IOUPserial_GetError(IOUPserial_TError *Err);
/*
** ===================================================================
**     Method      :  IOUPserial_GetError (component AsynchroSerial)
**     Description :
**         Returns a set of errors on the channel (errors that cannot
**         be returned by given methods). The errors accumulate in a
**         set; after calling [GetError] this set is returned and
**         cleared.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Err             - Pointer to the returned set of errors
**     Returns     :
**         ---             - Error code (if GetError did not succeed),
**                           possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/

void IOUPserial_Interrupt(void);
/*
** ===================================================================
**     Method      :  IOUPserial_Interrupt (component AsynchroSerial)
**
**     Description :
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

void IOUPserial_Init(void);
/*
** ===================================================================
**     Method      :  IOUPserial_Init (component AsynchroSerial)
**
**     Description :
**         Initializes the associated peripheral(s) and the component 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

#define IOUPserial_TurnRxOff() setReg8(UCR0, UCR0_RC1_BITMASK)
/*
** ===================================================================
**     Method      :  IOUPserial_TurnRxOff (component AsynchroSerial)
**     Description :
**         Turns off the receiver. This method is available only if the
**         receiver property is enabled.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define IOUPserial_TurnRxOn() setReg8(UCR0, UCR0_RC0_BITMASK)
/*
** ===================================================================
**     Method      :  IOUPserial_TurnRxOn (component AsynchroSerial)
**     Description :
**         Turns on the receiver. This method is available only if the
**         receiver property is enabled.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define IOUPserial_TurnTxOff() setReg8(UCR0, UCR0_TC1_BITMASK)
/*
** ===================================================================
**     Method      :  IOUPserial_TurnTxOff (component AsynchroSerial)
**     Description :
**         Turns off the transmitter. This method is available only if
**         the transmitter property is enabled.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define IOUPserial_TurnTxOn() setReg8(UCR0, UCR0_TC0_BITMASK)
/*
** ===================================================================
**     Method      :  IOUPserial_TurnTxOn (component AsynchroSerial)
**     Description :
**         Turns on the transmitter. This method is available only if
**         the transmitter property is enabled.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define IOUPserial_GetTxComplete() testReg8Bit(USR0, TXEMP)
/*
** ===================================================================
**     Method      :  IOUPserial_GetTxComplete (component AsynchroSerial)
**     Description :
**         Returns whether the transmitter is finished transmitting all
**         data, preamble, and break characters and is idle. It can be
**         used to determine when it is safe to switch a line driver (e.
**         g. in RS-485 applications). This method is available only if
**         event <OnTxComplete> is disabled.
**     Parameters  : None
**     Returns     :
**         ---             - Transmission process completeness.
** ===================================================================
*/



/* END IOUPserial. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale MCF series of microcontrollers.
**
** ###################################################################
*/

#endif /* ifndef __IOUPserial */
