/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : IOUPserial.c
**     Project     : 39_16_52_IN1UP
**     Processor   : MCF52233CAF60
**     Component   : AsynchroSerial
**     Version     : Component 02.611, Driver 01.02, CPU db: 3.00.000
**     Compiler    : CodeWarrior MCF C Compiler
**     Date/Time   : 2022-09-13, 17:04, # CodeGen: 0
**     Abstract    :
**         This component "AsynchroSerial" implements an asynchronous serial
**         communication. The component supports different settings of
**         parity, word width, stop-bit and communication speed,
**         user can select interrupt or polling handler.
**         Communication speed can be changed also in runtime.
**         The component requires one on-chip asynchronous serial channel.
**     Settings    :
**         Serial channel              : UART0
**
**         Protocol
**             Init baud rate          : 19200baud
**             Width                   : 8 bits
**             Stop bits               : 1.000
**             Parity                  : none
**             Breaks                  : Disabled
**             Input buffer size       : 30
**             Output buffer size      : 100
**
**         Registers
**             Input buffer            : URB0      [0x020C]
**             Output buffer           : UTB0      [0x020C]
**             Control register        : UMR10     [0x0200]
**             Mode register           : UMR20     [0x0200]
**             Baud setting reg.       : UCSR0     [0x0204]
**
**         Input interrupt
**             Vector name             : INT_UART0
**             Priority                : 430
**
**         Output interrupt
**             Vector name             : INT_UART0
**             Priority                : 430
**
**         Used pins:
**         ----------------------------------------------------------
**           Function | On package           |    Name
**         ----------------------------------------------------------
**            Input   |     21               |  URXD0_FEC_RXD0_PUA1
**            Output  |     22               |  UTXD0_FEC_CRS_PUA0
**         ----------------------------------------------------------
**
**
**
**     Contents    :
**         EnableEvent     - byte IOUPserial_EnableEvent(void);
**         DisableEvent    - byte IOUPserial_DisableEvent(void);
**         RecvChar        - byte IOUPserial_RecvChar(IOUPserial_TComData *Chr);
**         SendChar        - byte IOUPserial_SendChar(IOUPserial_TComData Chr);
**         RecvBlock       - byte IOUPserial_RecvBlock(IOUPserial_TComData *Ptr, word Size, word *Rcv);
**         SendBlock       - byte IOUPserial_SendBlock(IOUPserial_TComData *Ptr, word Size, word *Snd);
**         ClearRxBuf      - byte IOUPserial_ClearRxBuf(void);
**         ClearTxBuf      - byte IOUPserial_ClearTxBuf(void);
**         CharsInRxBuf    - byte IOUPserial_CharsInRxBuf(word *Chr);
**         GetCharsInRxBuf - word IOUPserial_GetCharsInRxBuf(void);
**         CharsInTxBuf    - byte IOUPserial_CharsInTxBuf(word *Chr);
**         GetCharsInTxBuf - word IOUPserial_GetCharsInTxBuf(void);
**         GetError        - byte IOUPserial_GetError(IOUPserial_TError *Err);
**         TurnTxOn        - void IOUPserial_TurnTxOn(void);
**         TurnTxOff       - void IOUPserial_TurnTxOff(void);
**         TurnRxOn        - void IOUPserial_TurnRxOn(void);
**         TurnRxOff       - void IOUPserial_TurnRxOff(void);
**         GetTxComplete   - bool IOUPserial_GetTxComplete(void);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file IOUPserial.c
** @version 01.02
** @brief
**         This component "AsynchroSerial" implements an asynchronous serial
**         communication. The component supports different settings of
**         parity, word width, stop-bit and communication speed,
**         user can select interrupt or polling handler.
**         Communication speed can be changed also in runtime.
**         The component requires one on-chip asynchronous serial channel.
*/         
/*!
**  @addtogroup IOUPserial_module IOUPserial module documentation
**  @{
*/         

/* MODULE IOUPserial. */

#include "IOUPserial.h"
#include "Events.h"


#define OVERRUN_ERR      0x01          /* Overrun error flag bit    */
#define FRAMING_ERR      0x02          /* Framing error flag bit    */
#define PARITY_ERR       0x04          /* Parity error flag bit     */
#define CHAR_IN_RX       0x08          /* Char is in RX buffer      */
#define FULL_TX          0x10          /* Full transmit buffer      */
#define RUNINT_FROM_TX   0x20          /* Interrupt is in progress  */
#define FULL_RX          0x40          /* Full receive buffer       */
#define ENABLED_TX_INT   0x80          /* TX interrupt enabled      */
#define BREAK_ERR        0x0200        /* Break detect              */

volatile bool EnEvent;                 /* Enable/Disable events */
static volatile word SerFlag;          /* Flags for serial communication */
                                       /* Bits: 0 - OverRun error */
                                       /*       1 - Framing error */
                                       /*       2 - Parity error */
                                       /*       3 - Char in RX buffer */
                                       /*       4 - Full TX buffer */
                                       /*       5 - Running int from TX */
                                       /*       6 - Full RX buffer */
                                       /*       7 - TX interrupt enabled */
                                       /*       8 - Unused  */
                                       /*       9 - Break detected  */
                                       /*      10 - Unused */
                                       /*      11 - Unused */
static volatile word ErrFlag;          /* Error flags mirror of SerFlag */
volatile word IOUPserial_InpLen;       /* Length of input buffer's content */
static volatile IOUPserial_TComData *InpPtrR; /* Pointer for reading from input buffer */
static volatile IOUPserial_TComData *InpPtrW; /* Pointer for writing to input buffer */
static volatile IOUPserial_TComData InpBuffer[IOUPserial_INP_BUF_SIZE]; /* Input buffer for serial commmunication */
volatile word IOUPserial_OutLen;       /* Length of output bufer's content */
static volatile IOUPserial_TComData *OutPtrR; /* Pointer for reading from output buffer */
static volatile IOUPserial_TComData *OutPtrW; /* Pointer for writing to output buffer */
static volatile IOUPserial_TComData OutBuffer[IOUPserial_OUT_BUF_SIZE]; /* Output buffer for serial commmunication */

/*
** ===================================================================
**     Method      :  HWEnDi (component AsynchroSerial)
**
**     Description :
**         Enables or disables the peripheral(s) associated with the 
**         component. The method is called automatically as a part of the 
**         Enable and Disable methods and several internal methods.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void HWEnDi(void)
{
  setReg8(UCR0, (UCR0_TC0_BITMASK | UCR0_RC0_BITMASK)); /* Enable receiver and transmitter */
  setReg8(UIMR0, 0x02);                /* Enable receiver interrupt */
}

/*
** ===================================================================
**     Method      :  IOUPserial_EnableEvent (component AsynchroSerial)
**     Description :
**         Enables the events. This method is available if the
**         interrupt service/event property is enabled and at least one
**         event is enabled.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte IOUPserial_EnableEvent(void)
{
  EnEvent = TRUE;                      /* Set the flag "events enabled" */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  IOUPserial_DisableEvent (component AsynchroSerial)
**     Description :
**         Disables the events. This method is available if the
**         interrupt service/event property is enabled and at least one
**         event is enabled.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte IOUPserial_DisableEvent(void)
{
  EnEvent = FALSE;                     /* Set the flag "events disabled" */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  IOUPserial_RecvChar (component AsynchroSerial)
**     Description :
**         If any data is received, this method returns one character,
**         otherwise it returns an error code (it does not wait for
**         data). This method is enabled only if the receiver property
**         is enabled.
**         [Note:] Because the preferred method to handle error and
**         break exception in the interrupt mode is to use events
**         <OnError> and <OnBreak> the return value ERR_RXEMPTY has
**         higher priority than other error codes. As a consequence the
**         information about an exception in interrupt mode is returned
**         only if there is a valid character ready to be read.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Chr             - Pointer to a received character
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_RXEMPTY - No data in receiver
**                           ERR_BREAK - Break character is detected
**                           (only when the <Interrupt service> property
**                           is disabled and the <Break signal> property
**                           is enabled)
**                           ERR_COMMON - common error occurred (the
**                           <GetError> method can be used for error
**                           specification)
** ===================================================================
*/
byte IOUPserial_RecvChar(IOUPserial_TComData *Chr)
{
  register byte Result = ERR_OK;       /* Return error code */

  if (IOUPserial_InpLen > 0x00) {      /* Is number of received chars greater than 0? */
    EnterCritical();                   /* Disable global interrupts */
    IOUPserial_InpLen--;               /* Decrease number of received chars */
    *Chr = *(InpPtrR++);               /* Received char */
    if (InpPtrR >= (InpBuffer + IOUPserial_INP_BUF_SIZE)) { /* Is the pointer out of the receive buffer? */
      InpPtrR = InpBuffer;             /* Set pointer to the first item into the receive buffer */
    }
    Result = (byte)((SerFlag & (OVERRUN_ERR | FRAMING_ERR | PARITY_ERR | FULL_RX))? ERR_COMMON : ERR_OK);
    SerFlag &= ~(OVERRUN_ERR | FRAMING_ERR | PARITY_ERR | FULL_RX | CHAR_IN_RX); /* Clear all errors in the status variable */
    ExitCritical();                    /* Enable global interrupts */
  } else {
    return ERR_RXEMPTY;                /* Receiver is empty */
  }
  return Result;                       /* Return error code */
}

/*
** ===================================================================
**     Method      :  IOUPserial_SendChar (component AsynchroSerial)
**     Description :
**         Sends one character to the channel. If the component is
**         temporarily disabled (Disable method) SendChar method only
**         stores data into an output buffer. In case of a zero output
**         buffer size, only one character can be stored. Enabling the
**         component (Enable method) starts the transmission of the
**         stored data. This method is available only if the
**         transmitter property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Chr             - Character to send
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_TXFULL - Transmitter is full
** ===================================================================
*/
byte IOUPserial_SendChar(IOUPserial_TComData Chr)
{
  if (IOUPserial_OutLen == IOUPserial_OUT_BUF_SIZE) { /* Is number of chars in buffer is the same as a size of the transmit buffer */
    return ERR_TXFULL;                 /* If yes then error */
  }
  EnterCritical();                     /* Disable global interrupts */
  IOUPserial_OutLen++;                 /* Increase number of bytes in the transmit buffer */
  *(OutPtrW++) = Chr;                  /* Store char to buffer */
  if (OutPtrW >= (OutBuffer + IOUPserial_OUT_BUF_SIZE)) { /* Is the pointer out of the transmit buffer */
    OutPtrW = OutBuffer;               /* Set pointer to first item in the transmit buffer */
  }
  SerFlag |= ENABLED_TX_INT;           /* Set the flag ENABLED_TX_INT */
  setReg8(UIMR0, 0x03);                /* Enable transmit interrupt */
  ExitCritical();                      /* Enable global interrupts */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  IOUPserial_RecvBlock (component AsynchroSerial)
**     Description :
**         If any data is received, this method returns the block of
**         the data and its length (and incidental error), otherwise it
**         returns an error code (it does not wait for data).
**         This method is available only if non-zero length of the
**         input buffer is defined and the receiver property is enabled.
**         If less than requested number of characters is received only
**         the available data is copied from the receive buffer to the
**         user specified destination. The value ERR_EXEMPTY is
**         returned and the value of variable pointed by the Rcv
**         parameter is set to the number of received characters.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Ptr             - Pointer to the block of received data
**         Size            - Size of the block
**       * Rcv             - Pointer to real number of the received data
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_RXEMPTY - The receive buffer didn't
**                           contain the requested number of data. Only
**                           available data has been returned.
**                           ERR_COMMON - common error occurred (the
**                           GetError method can be used for error
**                           specification)
** ===================================================================
*/
byte IOUPserial_RecvBlock(IOUPserial_TComData *Ptr,word Size,word *Rcv)
{
  register word count;                 /* Number of received chars */
  register byte result = ERR_OK;       /* Last error */

  for(count = 0; count < Size; count++) {
    switch ( IOUPserial_RecvChar(Ptr++)) {
    case ERR_RXEMPTY:
      if (result == ERR_OK) {
        result = ERR_RXEMPTY;
      }
     *Rcv = count;                     /* Return number of received chars */
      return result;
      break;
    case ERR_COMMON:
      result = ERR_COMMON;             /* Return the info that an error was detected */
      break;
    default:
      break;
    }
  }
  *Rcv = count;                        /* Return number of received chars */
  return result;                       /* Return last error code */
}

/*
** ===================================================================
**     Method      :  IOUPserial_SendBlock (component AsynchroSerial)
**     Description :
**         Sends a block of characters to the channel.
**         This method is available only if non-zero length of the
**         output buffer is defined and the transmitter property is
**         enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Ptr             - Pointer to the block of data to send
**         Size            - Size of the block
**       * Snd             - Pointer to number of data that are sent
**                           (moved to buffer)
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_TXFULL - It was not possible to send
**                           requested number of bytes
** ===================================================================
*/
byte IOUPserial_SendBlock(IOUPserial_TComData *Ptr,word Size,word *Snd)
{
  register word count;                 /* Number of sent chars */
  register byte result = ERR_OK;       /* Last error */

  for (count = 0x00; count < Size; count++) {
    result = IOUPserial_SendChar(*Ptr++);
    if (result != ERR_OK) {            /* Sending given number of chars */
      *Snd = count;                    /* Return number of sent chars */
      return result;                   /* Return last error */
    }
  }
  *Snd = count;                        /* Return number of sended chars */
  return result;                       /* Return error code */
}

/*
** ===================================================================
**     Method      :  IOUPserial_ClearRxBuf (component AsynchroSerial)
**     Description :
**         Clears the receive buffer.
**         This method is available only if non-zero length of the
**         input buffer is defined and the receiver property is enabled.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte IOUPserial_ClearRxBuf(void)
{
  EnterCritical();                     /* Disable global interrupts */
  IOUPserial_InpLen = 0x00;            /* Set number of chars in the transmit buffer to 0 */
  InpPtrR = InpPtrW = InpBuffer;       /* Set pointers on the first item in the transmit buffer */
  ExitCritical();                      /* Enable global interrupts */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  IOUPserial_ClearTxBuf (component AsynchroSerial)
**     Description :
**         Clears the transmit buffer.
**         This method is available only if non-zero length of the
**         output buffer is defined and the receiver property is
**         enabled.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte IOUPserial_ClearTxBuf(void)
{
  EnterCritical();                     /* Disable global interrupts */
  IOUPserial_OutLen = 0x00;            /* Set number of chars in the receive buffer to 0 */
  OutPtrR = OutPtrW = OutBuffer;       /* Set pointers on the first item in the receive buffer */
  ExitCritical();                      /* Enable global interrupts */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  IOUPserial_CharsInRxBuf (component AsynchroSerial)
**     Description :
**         Returns the number of characters in the input buffer. This
**         method is available only if the receiver property is enabled.
**         [deprecated method]
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Chr             - Pointer to the number of characters in the
**                           input buffer
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte IOUPserial_CharsInRxBuf(word *Chr)
{
  *Chr = IOUPserial_InpLen;            /* Return number of chars in receive buffer */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  IOUPserial_GetCharsInRxBuf (component AsynchroSerial)
**     Description :
**         Returns the number of characters in the input buffer. This
**         method is available only if the receiver property is enabled.
**     Parameters  : None
**     Returns     :
**         ---             - The number of characters in the input
**                           buffer.
** ===================================================================
*/
word IOUPserial_GetCharsInRxBuf(void)
{
  return IOUPserial_InpLen;            /* Return number of chars in receive buffer */
}

/*
** ===================================================================
**     Method      :  IOUPserial_CharsInTxBuf (component AsynchroSerial)
**     Description :
**         Returns the number of characters in the output buffer. This
**         method is available only if the transmitter property is
**         enabled.
**         [deprecated method]
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Chr             - Pointer to the number of characters in the
**                           output buffer
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte IOUPserial_CharsInTxBuf(word *Chr)
{
  *Chr = IOUPserial_OutLen;            /* Return number of chars in transmit buffer */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  IOUPserial_GetCharsInTxBuf (component AsynchroSerial)
**     Description :
**         Returns the number of characters in the output buffer. This
**         method is available only if the transmitter property is
**         enabled.
**     Parameters  : None
**     Returns     :
**         ---             - The number of characters in the output
**                           buffer.
** ===================================================================
*/
word IOUPserial_GetCharsInTxBuf(void)
{
  return IOUPserial_OutLen;            /* Return number of chars in the transmitter buffer */
}

/*
** ===================================================================
**     Method      :  IOUPserial_GetError (component AsynchroSerial)
**     Description :
**         Returns a set of errors on the channel (errors that cannot
**         be returned by given methods). The errors accumulate in a
**         set; after calling [GetError] this set is returned and
**         cleared.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Err             - Pointer to the returned set of errors
**     Returns     :
**         ---             - Error code (if GetError did not succeed),
**                           possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte IOUPserial_GetError(IOUPserial_TError *Err)
{
  EnterCritical();                     /* Disable global interrupts */
  Err->err = 0;
  Err->errName.OverRun = ((ErrFlag & OVERRUN_ERR) != 0x00); /* Overrun error */
  Err->errName.Framing = ((ErrFlag & FRAMING_ERR ) != 0x00); /* Framing error */
  Err->errName.Parity = ((ErrFlag & PARITY_ERR) != 0x00); /* Parity error */
  Err->errName.RxBufOvf = ((ErrFlag & FULL_RX) != 0x00); /* Buffer overflow */
  ErrFlag = 0;                         /* Clear error flags */
  ExitCritical();                      /* Enable global interrupts */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  IOUPserial_InterruptRx (component AsynchroSerial)
**
**     Description :
**         The method services the receive interrupt of the selected 
**         peripheral(s) and eventually invokes the component's event(s).
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
#define ON_ERROR    1
#define ON_FULL_RX  2
#define ON_RX_CHAR  4
static void IOUPserial_InterruptRx(void)
{
  register IOUPserial_TComData Data;   /* Temporary variable for data */
  register byte OnFlags = 0x00;        /* Temporary variable for flags */

  Data = (IOUPserial_TComData)getReg8(URB0); /* Read data from the receiver */
  if (IOUPserial_InpLen < IOUPserial_INP_BUF_SIZE) { /* Is number of bytes in the receive buffer lower than size of buffer? */
    IOUPserial_InpLen++;               /* Increse number of chars in the receive buffer */
    *(InpPtrW++) = Data;               /* Save received char to the receive buffer */
    if (InpPtrW >= (InpBuffer + IOUPserial_INP_BUF_SIZE)) { /* Is the pointer out of the receive buffer? */
      InpPtrW = InpBuffer;             /* Set pointer on the first item into the receive buffer */
    }
    OnFlags |= ON_RX_CHAR;             /* Set flag "OnRXChar" */
    if (IOUPserial_InpLen == IOUPserial_INP_BUF_SIZE) { /* Is number of bytes in the receive buffer equal as a size of buffer? */
      OnFlags |= ON_FULL_RX;           /* If yes then set flag "OnFullRxBuff" */
    }
  } else {
    SerFlag |= FULL_RX;                /* If yes then set flag buffer overflow */
    ErrFlag |= FULL_RX;
    OnFlags |= ON_ERROR;               /* Set flag "OnError" */
  }
  if (EnEvent) {                       /* Are the events enabled? */
    if (OnFlags & ON_ERROR) {          /* Is error flag set? */
      IOUPserial_OnError();            /* If yes then invoke user event */
    } else {
      if (OnFlags & ON_RX_CHAR) {      /* Is OnRxChar flag set? */
        IOUPserial_OnRxChar();         /* If yes then invoke user event */
      }
      if (OnFlags & ON_FULL_RX) {      /* Is OnFullRxBuf flag set? */
        IOUPserial_OnFullRxBuf();      /* If yes then invoke user event */
      }
    }
  }
}

/*
** ===================================================================
**     Method      :  IOUPserial_InterruptTx (component AsynchroSerial)
**
**     Description :
**         The method services the receive interrupt of the selected 
**         peripheral(s) and eventually invokes the component's event(s).
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
#define ON_FREE_TX  1
#define ON_TX_CHAR  2
static void IOUPserial_InterruptTx(void)
{
  register byte OnFlags = 0x00;        /* Temporary variable for flags */

  if (SerFlag & RUNINT_FROM_TX) {      /* Is flag "running int from TX" set? */
    OnFlags |= ON_TX_CHAR;             /* Set flag "OnTxChar" */
  }
  SerFlag &= ~RUNINT_FROM_TX;          /* Reset flag "running int from TX" */
  if (IOUPserial_OutLen) {             /* Is number of bytes in the transmit buffer greater then 0? */
    IOUPserial_OutLen--;               /* Decrease number of chars in the transmit buffer */
    SerFlag |= RUNINT_FROM_TX;         /* Set flag "running int from TX"? */
    setReg8(UTB0, (IOUPserial_TComData)*(OutPtrR++)); /* Store char to transmitter register */
    if (OutPtrR >= (OutBuffer + IOUPserial_OUT_BUF_SIZE)) { /* Is the pointer out of the transmit buffer? */
      OutPtrR = OutBuffer;             /* Set pointer on the first item into the transmit buffer */
    }
  } else {
    OnFlags |= ON_FREE_TX;             /* Set flag "OnFreeTxBuf" */
    SerFlag &= ~ENABLED_TX_INT;        /* Clear the flag ENABLED_TX_INT */
    setReg8(UIMR0, 0x02);              /* Disable transmit interrupt */
  }
  ErrFlag |= SerFlag;                  /* Add new error flags into the ErrorFlag status variable */
  if (EnEvent) {                       /* Are the events enabled? */
    if (OnFlags & ON_TX_CHAR) {        /* Is flag "OnTxChar" set? */
      IOUPserial_OnTxChar();           /* If yes then invoke user event */
    }
    if (OnFlags & ON_FREE_TX) {        /* Is flag "OnFreeTxBuf" set? */
      IOUPserial_OnFreeTxBuf();        /* If yes then invoke user event */
    }
  }
}

/*
** ===================================================================
**     Method      :  IOUPserial_Interrupt (component AsynchroSerial)
**
**     Description :
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
__declspec(interrupt) void IOUPserial_Interrupt(void)
{
  register word StatReg = getReg8(USR0); /* Read status register */
  register word OnFlags = 0;           /* Temporary variable for flags */

  if (StatReg & (USR0_RB_BITMASK | USR0_OE_BITMASK | USR0_FE_BITMASK | USR0_PE_BITMASK)) { /* Is any error flag set? */
    setReg8(UCR0, 0x40);               /* Reset error request flags */
    if (StatReg & USR0_RB_BITMASK) {   /* Is break detected? */
      OnFlags |= FRAMING_ERR;          /* If yes then set the flag */
    }
    if (StatReg & USR0_OE_BITMASK) {   /* Is overrun error flag set? */
      OnFlags |= OVERRUN_ERR;          /* If yes then set the flag */
    }
    if (StatReg & USR0_FE_BITMASK) {   /* Is framing error flag set? */
      OnFlags |= FRAMING_ERR;          /* If yes then set the flag */
    }
    if (StatReg & USR0_PE_BITMASK) {   /* Is parity error flag set? */
      OnFlags |= PARITY_ERR;           /* If yes then set the flag */
    }
    SerFlag |= OnFlags;                /* Copy flags status to SerFlag status variable */
    ErrFlag |= OnFlags;                /* Copy flags status to ErrFlag status variable */
    (void)getReg8(URB0);               /* Dummy read of data register - clear RXRDY bit */
    StatReg &= ~USR0_RXRDY_BITMASK;    /* Clear the receive data flag to discard the errorneous data */
    if (EnEvent) {                     /* Are the events enabled? */
      IOUPserial_OnError();            /* If yes then invoke user event */
    }
  }
  if (StatReg & USR0_RXRDY_BITMASK) {  /* Is the receiver interrupt flag set? */
    IOUPserial_InterruptRx();          /* If yes, then invoke the internal service routine. This routine is inlined. */
  }
  if (SerFlag & ENABLED_TX_INT) {      /* Is the transmitter interrupt enabled? */
    if (StatReg & USR0_TXRDY_BITMASK) { /* Is the transmitter ready? */
      IOUPserial_InterruptTx();        /* If yes, then invoke the internal service routine. This routine is inlined. */
    }
  }
}

/*
** ===================================================================
**     Method      :  IOUPserial_Init (component AsynchroSerial)
**
**     Description :
**         Initializes the associated peripheral(s) and the component 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void IOUPserial_Init(void)
{
  SerFlag = 0x00;                      /* Reset flags */
  EnEvent = FALSE;                     /* Disable events */
  /* UCR0: ??=0,MISC=3,TC=0,RC=0 */
  setReg8(UCR0, 0x30U);                /* Reset UART transmitter */ 
  /* UCR0: ??=0,MISC=2,TC=0,RC=0 */
  setReg8(UCR0, 0x20U);                /* Reset UART receiver */ 
  /* UMR10: RXRTS=0,RXIRQ=0,ERR=0,PM=2,PT=0,BC=3 */
  setReg8(UMR10, 0x13U);               /*  Set the UMR1 register */ 
  /* UMR20: CM=0,TXRTS=0,TXCTS=0,SB=7 */
  setReg8(UMR20, 0x07U);               /*  Set the UMR2 register */ 
  /* UCSR0: RCS=0x0D,TCS=0x0D */
  setReg8(UCSR0, 0xDDU);                
  IOUPserial_InpLen = 0x00;            /* No char in the receive buffer */
  InpPtrW = InpPtrR = InpBuffer;       /* Set pointer on the first item in the receive buffer */
  IOUPserial_OutLen = 0x00;            /* No char in the transmit buffer */
  OutPtrW = OutPtrR = OutBuffer;       /* Set pointer on the first item in the transmit buffer */
  /* UBG10: Divider_MSB=0 */
  setReg8(UBG10, 0x00U);                
  /* UBG20: Divider_LSB=0x51 */
  setReg8(UBG20, 0x51U);                
  HWEnDi();                            /* Enable/disable device according to status flags */
}

/*
** ===================================================================
**     Method      :  IOUPserial_TurnRxOff (component AsynchroSerial)
**     Description :
**         Turns off the receiver. This method is available only if the
**         receiver property is enabled.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void IOUPserial_TurnRxOff(void)

**      This method is implemented as a macro. See header module. **
*/

/*
** ===================================================================
**     Method      :  IOUPserial_TurnRxOn (component AsynchroSerial)
**     Description :
**         Turns on the receiver. This method is available only if the
**         receiver property is enabled.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void IOUPserial_TurnRxOn(void)

**      This method is implemented as a macro. See header module. **
*/

/*
** ===================================================================
**     Method      :  IOUPserial_TurnTxOff (component AsynchroSerial)
**     Description :
**         Turns off the transmitter. This method is available only if
**         the transmitter property is enabled.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void IOUPserial_TurnTxOff(void)

**      This method is implemented as a macro. See header module. **
*/

/*
** ===================================================================
**     Method      :  IOUPserial_TurnTxOn (component AsynchroSerial)
**     Description :
**         Turns on the transmitter. This method is available only if
**         the transmitter property is enabled.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void IOUPserial_TurnTxOn(void)

**      This method is implemented as a macro. See header module. **
*/

/*
** ===================================================================
**     Method      :  IOUPserial_GetTxComplete (component AsynchroSerial)
**     Description :
**         Returns whether the transmitter is finished transmitting all
**         data, preamble, and break characters and is idle. It can be
**         used to determine when it is safe to switch a line driver (e.
**         g. in RS-485 applications). This method is available only if
**         event <OnTxComplete> is disabled.
**     Parameters  : None
**     Returns     :
**         ---             - Transmission process completeness.
** ===================================================================
*/
/*
bool IOUPserial_GetTxComplete(void)

**      This method is implemented as a macro. See header module. **
*/


/* END IOUPserial. */


/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale MCF series of microcontrollers.
**
** ###################################################################
*/
