/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : SDATA.c
**     Project     : 39_16_52_IN1UP
**     Processor   : MCF52233CAF60
**     Component   : BitIO
**     Version     : Component 02.086, Driver 01.02, CPU db: 3.00.000
**     Compiler    : CodeWarrior MCF C Compiler
**     Date/Time   : 2022-09-13, 17:04, # CodeGen: 0
**     Abstract    :
**         This component "BitIO" implements an one-bit input/output.
**         It uses one bit/pin of a port.
**         Methods of this component are mostly implemented as a macros
**         (if supported by target language and compiler).
**     Settings    :
**         Used pin                    :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       54            |  IRQ2_FEC_RXD3_PNQ2
**             ----------------------------------------------------
**
**         Port name                   : PORTNQ
**
**         Bit number (in port)        : 2
**         Bit mask of the port        : 0x0004
**
**         Initial direction           : Output (direction can be changed)
**         Safe mode                   : no
**         Initial output value        : 0
**         Initial pull option         : up
**
**         Port data register          : PORTNQ    [0x00100008]
**         Port control register       : DDRNQ     [0x00100020]
**
**         Optimization for            : speed
**     Contents    :
**         SetDir - void SDATA_SetDir(bool Dir);
**         GetVal - bool SDATA_GetVal(void);
**         PutVal - void SDATA_PutVal(bool Val);
**         ClrVal - void SDATA_ClrVal(void);
**         SetVal - void SDATA_SetVal(void);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file SDATA.c
** @version 01.02
** @brief
**         This component "BitIO" implements an one-bit input/output.
**         It uses one bit/pin of a port.
**         Methods of this component are mostly implemented as a macros
**         (if supported by target language and compiler).
*/         
/*!
**  @addtogroup SDATA_module SDATA module documentation
**  @{
*/         

/* MODULE SDATA. */

#include "SDATA.h"
  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"


/*
** ===================================================================
**     Method      :  SDATA_GetVal (component BitIO)
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pin and returns it
**           b) direction = Output : returns the last written value
**     Parameters  : None
**     Returns     :
**         ---             - Input value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)

** ===================================================================
*/
bool SDATA_GetVal(void)
{
  if ((getReg8(DDRNQ) & 0x04U)) {
    return (bool)((getReg8(PORTNQ) & 0x04U)); /* Return port output data */
  } else { /* !(getReg8(DDRNQ) & 0x04U) */
    return (bool)((getReg8(SETNQ) & 0x04U)); /* Return port input data */
  } /* !(getReg8(DDRNQ) & 0x04U) */
}

/*
** ===================================================================
**     Method      :  SDATA_PutVal (component BitIO)
**     Description :
**         This method writes the new output value.
**         Note: If direction is set to input the method code may not
**               work properly.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val             - Output value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)
**     Returns     : Nothing
** ===================================================================
*/
void SDATA_PutVal(bool Val)
{
  if (Val) {
    setReg8(SETNQ, 0x04U);             /* SETNQ2=0x01U */
  } else { /* !Val */
    setReg8(CLRNQ, 0xFBU);             /* CLRNQ2=0x00U */
  } /* !Val */
}

/*
** ===================================================================
**     Method      :  SDATA_ClrVal (component BitIO)
**     Description :
**         This method clears (sets to zero) the output value.
**         Note: If direction is set to input the method code may not
**               work properly.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void SDATA_ClrVal(void)

**  This method is implemented as a macro. See SDATA.h file.  **
*/

/*
** ===================================================================
**     Method      :  SDATA_SetVal (component BitIO)
**     Description :
**         This method sets (sets to one) the output value.
**         Note: If direction is set to input the method code may not
**               work properly.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void SDATA_SetVal(void)

**  This method is implemented as a macro. See SDATA.h file.  **
*/

/*
** ===================================================================
**     Method      :  SDATA_SetDir (component BitIO)
**     Description :
**         This method sets direction of the component.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Dir        - Direction to set (FALSE or TRUE)
**                      FALSE = Input, TRUE = Output
**     Returns     : Nothing
** ===================================================================
*/
void SDATA_SetDir(bool Dir)
{
  if (Dir) {
    setReg8Bits(DDRNQ, 0x04U);         /* DDRNQ2=0x01U */
  } else { /* !Dir */
    clrReg8Bits(DDRNQ, 0x04U);         /* DDRNQ2=0x00U */
  } /* !Dir */
}


/* END SDATA. */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale MCF series of microcontrollers.
**
** ###################################################################
*/
