/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : RTC1.h
**     Project     : 40_03_01_IN3UP
**     Processor   : MCF52233CAF60
**     Component   : RTC
**     Version     : Component 01.240, Driver 01.05, CPU db: 3.00.000
**     Compiler    : CodeWarrior MCF C Compiler
**     Date/Time   : 2026-03-11, 17:59, # CodeGen: 0
**     Abstract    :
**         This component implements a real time clock. Actual date may also be
**         obtained and an alarm function is included.
**     Settings    :
**         Device type                 :  RTC
**
**         Interrupt service           : Enabled
**         Day register                : DAYS      [0x03E0]
**         Hour register               : HOURMIN   [0x03C0]
**         Minute register             : HOURMIN   [0x03C0]
**         Second register             : SECONDS   [0x03C4]
**         Alarm Day register          : ALRM_DAY  [0x03E4]
**         Alarm Hour register         : ALRM_HM   [0x03C8]
**         Alarm Minute register       : ALRM_HM   [0x03C8]
**         Alarm Second register       : ALRM_SEC  [0x03CC]
**
**         User handling procedure     : RTC1_OnAlarm
**         This event is called whenever the current time is equal
**         to alarm time
**
**         User handling procedure     : RTC1_OnSecond
**         This event is called on every increment of the second counter.
**
**         Initialization:
**              Component              : Enabled
**              Alarm                  : Enabled
**              Events                 : Enabled
**
**              Time                   : 0:0:0
**              Count of days          : 0
**              Alarm
**                    Day              : 0
**                    Hour             : 0
**                    Minute           : 0
**                    Second           : 0
**     Contents    :
**         Enable       - byte RTC1_Enable(void);
**         Disable      - byte RTC1_Disable(void);
**         EnableEvent  - byte RTC1_EnableEvent(void);
**         DisableEvent - byte RTC1_DisableEvent(void);
**         EnableAlarm  - byte RTC1_EnableAlarm(void);
**         DisableAlarm - byte RTC1_DisableAlarm(void);
**         SetAlarm     - byte RTC1_SetAlarm(byte Hour, byte Min, byte Sec);
**         SetAlarmDay  - byte RTC1_SetAlarmDay(word Day);
**         GetAlarm     - byte RTC1_GetAlarm(ALARMREC *Time);
**         GetAlarmDay  - byte RTC1_GetAlarmDay(word *Day);
**         SetTime      - byte RTC1_SetTime(byte Hour, byte Min, byte Sec);
**         GetTime      - byte RTC1_GetTime(TIMEREC *Time);
**         SetDay       - byte RTC1_SetDay(word Day);
**         GetDay       - byte RTC1_GetDay(word *Day);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file RTC1.h
** @version 01.05
** @brief
**         This component implements a real time clock. Actual date may also be
**         obtained and an alarm function is included.
*/         
/*!
**  @addtogroup RTC1_module RTC1 module documentation
**  @{
*/         

#ifndef __RTC1_H
#define __RTC1_H

/* MODULE RTC1. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"

#include "Cpu.h"

#ifndef __BWUserType_TIMEREC
#define __BWUserType_TIMEREC
  typedef struct {                     /* It contains actual number of hours, minutes, seconds. */
    byte Hour;                         /* hours (0 - 23) */
    byte Min;                          /* minutes (0 - 59) */
    byte Sec;                          /* seconds (0 - 59) */
  } TIMEREC;
#endif
#ifndef __BWUserType_DATEREC
#define __BWUserType_DATEREC
  typedef struct {                     /* It contains actual year, month, and day description. */
    word Year;                         /* years (1901 - 2099) */
    byte Month;                        /* months (1 - 12) */
    byte Day;                          /* days (0 - 28/29/30/31) */
  } DATEREC;
#endif
#ifndef __BWUserType_ALARMREC
#define __BWUserType_ALARMREC
  typedef struct {                     /* It contains an alarm time. */
    byte Hour;                         /* hours (0 - 23) */
    byte Min;                          /* minutes (0 - 59) */
    byte Sec;                          /* seconds (0 - 59) */
  } ALARMREC;
#endif



byte RTC1_Enable(void);
/*
** ===================================================================
**     Method      :  RTC1_Enable (component RTC)
**     Description :
**         Enable the component - it starts the signal generation.
**         Events can be disabled/enabled by
**         "DisableEvent"/"EnableEvent".
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_PROTECT - Registers are protected
**                           (MC68HC908LK24/MC68HC908LJ24 derivatives
**                           only)
** ===================================================================
*/

byte RTC1_Disable(void);
/*
** ===================================================================
**     Method      :  RTC1_Disable (component RTC)
**     Description :
**         Disable the component - it stops signal generation and
**         events calling.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_PROTECT - Registers are protected
**                           (MC68HC908LK24/MC68HC908LJ24 derivatives
**                           only)
** ===================================================================
*/

byte RTC1_EnableEvent(void);
/*
** ===================================================================
**     Method      :  RTC1_EnableEvent (component RTC)
**     Description :
**         This method enables the events. This method is available
**         only if any event is selected in the component.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
** ===================================================================
*/

byte RTC1_DisableEvent(void);
/*
** ===================================================================
**     Method      :  RTC1_DisableEvent (component RTC)
**     Description :
**         This method disables the events. This method is available
**         only if any event is selected in the component.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
** ===================================================================
*/

byte RTC1_EnableAlarm(void);
/*
** ===================================================================
**     Method      :  RTC1_EnableAlarm (component RTC)
**     Description :
**         Enable alarm of the RTC (method is available only when the
**         event OnAlarm is generated - <"generate code">).
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
** ===================================================================
*/

byte RTC1_DisableAlarm(void);
/*
** ===================================================================
**     Method      :  RTC1_DisableAlarm (component RTC)
**     Description :
**         Disable alarm of the RTC. (method is available only when the
**         event OnAlarm is generated - <"generate code"> )
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
** ===================================================================
*/

byte RTC1_SetAlarm(byte Hour, byte Min, byte Sec);
/*
** ===================================================================
**     Method      :  RTC1_SetAlarm (component RTC)
**     Description :
**         Set alarm time (hour, minute and second). (method is
**         available only when the event OnAlarm is generated -
**         <"generate code">)
**     Parameters  :
**         NAME            - DESCRIPTION
**         Hour            - Hours (0 - 23)
**         Min             - Minute (0 - 59)
**         Sec             - Seconds (0 - 59)
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_RANGE - Parameter out of range
** ===================================================================
*/

byte RTC1_SetAlarmDay(word Day);
/*
** ===================================================================
**     Method      :  RTC1_SetAlarmDay (component RTC)
**     Description :
**         Set alarm day. (method is available only when the event
**         OnAlarm is generated - <"generate code">)
**     Parameters  :
**         NAME            - DESCRIPTION
**         Day             - Days (0-65535)
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
** ===================================================================
*/

byte RTC1_GetAlarm(ALARMREC *Time);
/*
** ===================================================================
**     Method      :  RTC1_GetAlarm (component RTC)
**     Description :
**         Get alarm time (hour and minute) in ALARMREC structure.
**         (method is available only when the event OnAlarm is
**         generated - <"generate code">)
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Time            - Pointer to the ALARMREC structure. It
**                           contains hour and minute.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
** ===================================================================
*/

byte RTC1_GetAlarmDay(word *Day);
/*
** ===================================================================
**     Method      :  RTC1_GetAlarmDay (component RTC)
**     Description :
**         Get alarm day. (method is available only when the event
**         OnAlarm is generated - <"generate code">)
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Day             - Pointer to returned variable.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
** ===================================================================
*/

byte RTC1_SetTime(byte Hour, byte Min, byte Sec);
/*
** ===================================================================
**     Method      :  RTC1_SetTime (component RTC)
**     Description :
**         Set a new actual time (hour, minute and second).
**     Parameters  :
**         NAME            - DESCRIPTION
**         Hour            - Hours (0 - 23)
**         Min             - Minutes (0 - 59)
**         Sec             - Seconds (0 - 59)
**     Returns     :
**         ---             - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_RANGE - Parameter out of range
**                           - ERR_PROTECT - Registers are protected
**                           (MC68HC908LK24/MC68HC908LJ24 derivatives
**                           only) 
**                           - ERR_ENABLED - Device is enabled. Write to
**                           registers is not possible (56800 family
**                           only) 
**                           - ERR_BUSY - Device is busy
** ===================================================================
*/

byte RTC1_SetDay(word Day);
/*
** ===================================================================
**     Method      :  RTC1_SetDay (component RTC)
**     Description :
**         Set a new actual count of days.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Day             - Days (0-65535)
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
** ===================================================================
*/

byte RTC1_GetTime(TIMEREC *Time);
/*
** ===================================================================
**     Method      :  RTC1_GetTime (component RTC)
**     Description :
**         Get current time (hour, minute and second).
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Time            - Pointer to the structure TIMEREC. It
**                           contains actual number of hours, minutes
**                           and seconds.
**     Returns     :
**         ---             - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_BUSY - Device is busy
** ===================================================================
*/

byte RTC1_GetDay(word *Day);
/*
** ===================================================================
**     Method      :  RTC1_GetDay (component RTC)
**     Description :
**         Get current count of days.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Day             - Pointer to returned variable.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
** ===================================================================
*/

void RTC1_Init(void);
/*
** ===================================================================
**     Method      :  RTC1_Init (component RTC)
**
**     Description :
**         Initializes the associated peripheral(s) and the component 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

void RTC1_Interrupt(void);
/*
** ===================================================================
**     Method      :  RTC1_Interrupt (component RTC)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes event(s) of the component.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

/* END RTC1. */

#endif
/* ifndef __RTC1_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale MCF series of microcontrollers.
**
** ###################################################################
*/
