/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : TACHO.c
**     Project     : 39_16_50_IN1UP
**     Processor   : MCF52233CAF60
**     Component   : Capture
**     Version     : Component 02.223, Driver 01.04, CPU db: 3.00.000
**     Compiler    : CodeWarrior MCF C Compiler
**     Date/Time   : 2022-04-20, 15:58, # CodeGen: 0
**     Abstract    :
**         This component "Capture" simply implements the capture function
**         of timer. The counter counts the same way as in free run mode. On
**         the selected edge of the input signal (on the input pin), the current
**         content of the counter register is written into the capture
**         register and the OnCapture event is called.
**     Settings    :
**             Timer capture encapsulation : Capture
**
**         Timer
**             Timer                   : GPTA_Counter
**             Counter shared          : Yes
**
**         High speed mode
**             Prescaler               : divide-by-8
**           Maximal time for capture register
**             Xtal ticks              : 233017
**             microseconds            : 21070
**             milliseconds            : 21
**             seconds (real)          : 0.021069958848
**             Hz                      : 47
**           One tick of timer is
**             nanoseconds             : 333.333333333333
**
**         Initialization:
**              Timer                  : Enabled
**              Events                 : Enabled
**
**         Timer registers
**              Capture                : GPTC2     [0x001A0014]
**              Counter                : GPTCNT    [0x001A0004]
**              Mode                   : GPTCTL2   [0x001A000B]
**              Run                    : GPTCTL1   [0x001A0009]
**              Prescaler              : GPTCTL2   [0x001A000B]
**
**         Used input pin              : 
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       76            |  GPT2_FEC_TXD2_PWM5_PTA2
**             ----------------------------------------------------
**
**         Port name                   : PORTTA
**         Bit number (in port)        : 2
**         Bit mask of the port        : 0x0004
**
**         Signal edge/level           : rising
**         Priority                    : 610
**
**     Contents    :
**         Enable          - byte TACHO_Enable(void);
**         Disable         - byte TACHO_Disable(void);
**         EnableEvent     - byte TACHO_EnableEvent(void);
**         DisableEvent    - byte TACHO_DisableEvent(void);
**         Reset           - byte TACHO_Reset(void);
**         GetCaptureValue - byte TACHO_GetCaptureValue(TACHO_TCapturedValue *Value);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file TACHO.c
** @version 01.04
** @brief
**         This component "Capture" simply implements the capture function
**         of timer. The counter counts the same way as in free run mode. On
**         the selected edge of the input signal (on the input pin), the current
**         content of the counter register is written into the capture
**         register and the OnCapture event is called.
*/         
/*!
**  @addtogroup TACHO_module TACHO module documentation
**  @{
*/         

/* MODULE TACHO. */

#include "Events.h"
#include "TACHO.h"

static bool EnUser;                    /* Enable/Disable device by user */
static bool EnEvent;                   /* Enable/Disable events */
static TACHO_TCapturedValue CntrState; /* Content of counter */

/* Internal method prototypes */
void HWEnDi(void);

/*
** ===================================================================
**     Method      :  TACHO_Enable (component Capture)
**     Description :
**         This method enables the component - it starts the capture.
**         Events may be generated (<DisableEvent>/<EnableEvent>).
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte TACHO_Enable(void)
{
  if (!EnUser) {                       /* Is the device disabled by user? */
    EnUser = TRUE;                     /* If yes then set the flag "device enabled" */
    HWEnDi();                          /* Enable the device */
  }
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  TACHO_Disable (component Capture)
**     Description :
**         This method disables the component - it stops the capture.
**         No events will be generated.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte TACHO_Disable(void)
{
  if (EnUser) {                        /* Is the device enabled by user? */
    EnUser = FALSE;                    /* If yes then set the flag "device disabled" */
    HWEnDi();                          /* Disable the device */
  }
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  TACHO_EnableEvent (component Capture)
**     Description :
**         This method enables the events. This method is available
**         only if any event is selected.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte TACHO_EnableEvent(void)
{
  EnEvent = TRUE;                      /* Set the flag "events enabled" */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  TACHO_DisableEvent (component Capture)
**     Description :
**         This method disables the events.  This method is available
**         only if any event is selected.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte TACHO_DisableEvent(void)
{
  EnEvent = FALSE;                     /* Set the flag "events disabled" */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  TACHO_Reset (component Capture)
**     Description :
**         This method resets the counter register (see implementation
**         note in <General Info>).
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte TACHO_Reset(void)
{
  CntrState = getReg16(GPTCNT);        /* Load content of counter register to variable CntrState */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  TACHO_GetCaptureValue (component Capture)
**     Description :
**         This method gets the last value captured by enabled timer.
**         Note: one tick of timer is
**               333.333333333333 ns in high speed mode
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Value           - A pointer to the content of the
**                           capture register
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte TACHO_GetCaptureValue(TACHO_TCapturedValue *Value)
{
  *Value = getReg16(GPTC2);            /* Return captured value of counter register */
  *Value -= CntrState;                 /* Subtract counter state stored during last reset */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  TACHO_Init (component Capture)
**
**     Description :
**         Initializes the associated peripheral(s) and the component 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void TACHO_Init(void)
{
  /* GPTFLG1: ??=1,??=1 */
  setReg8Bits(GPTFLG1, 0x30U);         /* Clear capture flag */ 
  /* GPTIE: CI2=1 */
  setReg8Bits(GPTIE, 0x04U);           /* Enable interrupt */ 
  CntrState = getReg16(GPTCNT);        /* Initial state of variable */
  EnEvent = TRUE;                      /* Enable events */
  EnUser = TRUE;                       /* Enable device */
  HWEnDi();                            /* Enable/disable device according to status flags */
}

/*
** ===================================================================
**     Method      :  TACHO_Interrupt (component Capture)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes event(s) of the component.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
__declspec(interrupt) void TACHO_Interrupt(void)
{
  setReg8(GPTFLG1,0x04);               /* Reset interrupt request flag */
  if (EnEvent) {                       /* Are the events enabled? */
    TACHO_OnCapture();                 /* Invoke user event */
  }
}

/*
** ===================================================================
**     Method      :  HWEnDi (component Capture)
**
**     Description :
**         Enables or disables the peripheral(s) associated with the 
**         component. The method is called automatically as a part of the 
**         Enable and Disable methods and several internal methods.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void HWEnDi(void)
{
  if (EnUser) {                        /* Enable device? */
    setReg8Bits(GPTCTL2,0x10);         /* Enable capture */
  }
  else {                               /* Disable device? */
    clrReg8Bits(GPTCTL2,0x30);         /* Disable capture */
  }
}

/* END TACHO. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale MCF series of microcontrollers.
**
** ###################################################################
*/
