/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : LED56_COMM_WARN_MON.c
**     Project     : 40_03_01_IN3UP
**     Processor   : MCF52233CAF60
**     Component   : BitIO
**     Version     : Component 02.086, Driver 01.02, CPU db: 3.00.000
**     Compiler    : CodeWarrior MCF C Compiler
**     Date/Time   : 2026-03-11, 17:59, # CodeGen: 0
**     Abstract    :
**         This component "BitIO" implements an one-bit input/output.
**         It uses one bit/pin of a port.
**         Note: This component is set to work in Output direction only.
**         Methods of this component are mostly implemented as a macros
**         (if supported by target language and compiler).
**     Settings    :
**         Used pin                    :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       60            |  ACTLED_PLD0
**             ----------------------------------------------------
**
**         Port name                   : PORTLD
**
**         Bit number (in port)        : 0
**         Bit mask of the port        : 0x0001
**
**         Initial direction           : Output (direction cannot be changed)
**         Initial output value        : 0
**         Initial pull option         : up
**
**         Port data register          : PORTLD    [0x00100015]
**         Port control register       : DDRLD     [0x0010002D]
**         Port function register      : PLDPAR    [0x00100075]
**
**         Optimization for            : speed
**     Contents    :
**         GetVal - bool LED56_COMM_WARN_MON_GetVal(void);
**         PutVal - void LED56_COMM_WARN_MON_PutVal(bool Val);
**         ClrVal - void LED56_COMM_WARN_MON_ClrVal(void);
**         SetVal - void LED56_COMM_WARN_MON_SetVal(void);
**         NegVal - void LED56_COMM_WARN_MON_NegVal(void);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file LED56_COMM_WARN_MON.c
** @version 01.02
** @brief
**         This component "BitIO" implements an one-bit input/output.
**         It uses one bit/pin of a port.
**         Note: This component is set to work in Output direction only.
**         Methods of this component are mostly implemented as a macros
**         (if supported by target language and compiler).
*/         
/*!
**  @addtogroup LED56_COMM_WARN_MON_module LED56_COMM_WARN_MON module documentation
**  @{
*/         

/* MODULE LED56_COMM_WARN_MON. */

#include "LED56_COMM_WARN_MON.h"
  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"


/*
** ===================================================================
**     Method      :  LED56_COMM_WARN_MON_GetVal (component BitIO)
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pin and returns it
**           b) direction = Output : returns the last written value
**         Note: This component is set to work in Output direction only.
**     Parameters  : None
**     Returns     :
**         ---             - Input value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)

** ===================================================================
*/
/*
bool LED56_COMM_WARN_MON_GetVal(void)

**  This method is implemented as a macro. See LED56_COMM_WARN_MON.h file.  **
*/

/*
** ===================================================================
**     Method      :  LED56_COMM_WARN_MON_PutVal (component BitIO)
**     Description :
**         This method writes the new output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val             - Output value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)
**     Returns     : Nothing
** ===================================================================
*/
void LED56_COMM_WARN_MON_PutVal(bool Val)
{
  if (Val) {
    setReg8(SETLD, 0x01U);             /* SETLD0=0x01U */
  } else { /* !Val */
    setReg8(CLRLD, 0xFEU);             /* CLRLD0=0x00U */
  } /* !Val */
}

/*
** ===================================================================
**     Method      :  LED56_COMM_WARN_MON_ClrVal (component BitIO)
**     Description :
**         This method clears (sets to zero) the output value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void LED56_COMM_WARN_MON_ClrVal(void)

**  This method is implemented as a macro. See LED56_COMM_WARN_MON.h file.  **
*/

/*
** ===================================================================
**     Method      :  LED56_COMM_WARN_MON_SetVal (component BitIO)
**     Description :
**         This method sets (sets to one) the output value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void LED56_COMM_WARN_MON_SetVal(void)

**  This method is implemented as a macro. See LED56_COMM_WARN_MON.h file.  **
*/

/*
** ===================================================================
**     Method      :  LED56_COMM_WARN_MON_NegVal (component BitIO)
**     Description :
**         This method negates (inverts) the output value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void LED56_COMM_WARN_MON_NegVal(void)

**  This method is implemented as a macro. See LED56_COMM_WARN_MON.h file.  **
*/


/* END LED56_COMM_WARN_MON. */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale MCF series of microcontrollers.
**
** ###################################################################
*/
