/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : PE_Timer.c
**     Project     : 40_03_01_IN3UP
**     Processor   : MCF52233CAF60
**     Component   : PE_Timer
**     Version     : Driver 01.01
**     Compiler    : CodeWarrior MCF C Compiler
**     Date/Time   : 2026-03-11, 17:59, # CodeGen: 0
**     Abstract    :
**         This module "PE_Timer" implements internal methods and definitions
**         used by components working with timers.
**     Settings    :
**     Contents    :
**         No public methods
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file PE_Timer.c
** @version 01.01
** @brief
**         This module "PE_Timer" implements internal methods and definitions
**         used by components working with timers.
*/         
/*!
**  @addtogroup PE_Timer_module PE_Timer module documentation
**  @{
*/         


/* MODULE PE_Timer. */

#include "PE_Timer.h"

typedef union {
  dlong value;
  struct {
    dword part0;
    dword part1;
  } DW;
  struct {
    word part0;
    word part1;
    word part2;
    word part3;
  } W;
  struct {
    byte part0;
    byte part1;
    byte part2;
    byte part3;
    byte part4;
    byte part5;
    byte part6;
    byte part7;
  } B;
} PE_Timer_UINT64;

typedef union {
  struct {
    word value;
  } W;
  struct {
    byte part0;
    byte part1;
  } B;
} PE_Timer_UINT16;

/*
** ===================================================================
**     Method      :  PE_Timer_LngHi3 (component PE_Timer)
**
**     Description :
**         64bits number / 2^32 -> 16bits number. The method is called 
**         automatically as a part of several internal methods.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
bool PE_Timer_LngHi3(dlong In, word *Out) 
{
  PE_Timer_UINT64 *Input = (PE_Timer_UINT64*)&In;
  PE_Timer_UINT16 Mid;

  Mid.B.part0 = Input->B.part3;
  Mid.B.part1 = Input->B.part4;
  if ((Input->DW.part0 & 0xFFFFFF00UL) == 0) {
    if ((Input->B.part5 & 0x80) != 0) {
      if (Mid.W.value < 0xFFFF) {
        *Out = (word)(Mid.W.value + 1);
        return FALSE;
      } 
    }   
    else { 
      *Out = Mid.W.value;
      return FALSE;
    }  
  }
  *Out = Mid.W.value;
  return TRUE;
}

/*
** ===================================================================
**     Method      :  PE_Timer_LngHi4 (component PE_Timer)
**
**     Description :
**         64bits number / 2^40 -> 16bits number. The method is called 
**         automatically as a part of several internal methods.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
bool PE_Timer_LngHi4(dlong In, word *Out) 
{
  PE_Timer_UINT64 *Input = (PE_Timer_UINT64*)&In;

  if (Input->W.part0 == 0) {
    if ((Input->W.part2 & 0x8000) != 0) {
      if (Input->W.part1 < 0xFFFF) {
        *Out = (word)((Input->W.part1) + 1);
        return FALSE;
      }  
    }  
    else { 
      *Out = Input->W.part1;
      return FALSE;
    }  
  }
  *Out = Input->W.part1;
  return TRUE;
}

/* END PE_Timer. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale MCF series of microcontrollers.
**
** ###################################################################
*/
