/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : TACHO.h
**     Project     : 39_16_53_IN1UP
**     Processor   : MCF52233CAF60
**     Component   : Capture
**     Version     : Component 02.223, Driver 01.04, CPU db: 3.00.000
**     Compiler    : CodeWarrior MCF C Compiler
**     Date/Time   : 2022-09-28, 16:29, # CodeGen: 0
**     Abstract    :
**         This component "Capture" simply implements the capture function
**         of timer. The counter counts the same way as in free run mode. On
**         the selected edge of the input signal (on the input pin), the current
**         content of the counter register is written into the capture
**         register and the OnCapture event is called.
**     Settings    :
**             Timer capture encapsulation : Capture
**
**         Timer
**             Timer                   : GPTA_Counter
**             Counter shared          : Yes
**
**         High speed mode
**             Prescaler               : divide-by-8
**           Maximal time for capture register
**             Xtal ticks              : 233017
**             microseconds            : 21070
**             milliseconds            : 21
**             seconds (real)          : 0.021069958848
**             Hz                      : 47
**           One tick of timer is
**             nanoseconds             : 333.333333333333
**
**         Initialization:
**              Timer                  : Enabled
**              Events                 : Enabled
**
**         Timer registers
**              Capture                : GPTC2     [0x001A0014]
**              Counter                : GPTCNT    [0x001A0004]
**              Mode                   : GPTCTL2   [0x001A000B]
**              Run                    : GPTCTL1   [0x001A0009]
**              Prescaler              : GPTCTL2   [0x001A000B]
**
**         Used input pin              : 
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       76            |  GPT2_FEC_TXD2_PWM5_PTA2
**             ----------------------------------------------------
**
**         Port name                   : PORTTA
**         Bit number (in port)        : 2
**         Bit mask of the port        : 0x0004
**
**         Signal edge/level           : rising
**         Priority                    : 610
**
**     Contents    :
**         Enable          - byte TACHO_Enable(void);
**         Disable         - byte TACHO_Disable(void);
**         EnableEvent     - byte TACHO_EnableEvent(void);
**         DisableEvent    - byte TACHO_DisableEvent(void);
**         Reset           - byte TACHO_Reset(void);
**         GetCaptureValue - byte TACHO_GetCaptureValue(TACHO_TCapturedValue *Value);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file TACHO.h
** @version 01.04
** @brief
**         This component "Capture" simply implements the capture function
**         of timer. The counter counts the same way as in free run mode. On
**         the selected edge of the input signal (on the input pin), the current
**         content of the counter register is written into the capture
**         register and the OnCapture event is called.
*/         
/*!
**  @addtogroup TACHO_module TACHO module documentation
**  @{
*/         

#ifndef __TACHO_H
#define __TACHO_H

/* MODULE TACHO. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"

#include "Cpu.h"

#ifndef __BWUserType_TACHO_TCapturedValue
#define __BWUserType_TACHO_TCapturedValue
  typedef word TACHO_TCapturedValue;   /* Captured value, unsigned integer value. Bit-width of the type depends on the width of selected timer. */
#endif

#define TACHO_PRESCALER_VALUE 0x08UL   /* Initial prescaler value of the timer. It is available only if the component is enabled in high speed mode. */
#define TACHO_PRESCALER_VALUE_HIGH 0x08UL /* Prescaler value of the timer in high speed mode. It is available only if the component is enabled in high speed mode. */
#define TACHO_COUNTER_INPUT_CLOCK_HIGH 0x002F7600UL /* Counter input clock value in high speed mode [Hz] (integer number). It is available only if the component is enabled in high speed mode. */
#define TACHO_COUNTER_INPUT_CLOCK 0x002F7600UL /* Initial counter input clock value [Hz] (integer number). It is available only if the component is enabled in high speed mode. */


byte TACHO_Enable(void);
/*
** ===================================================================
**     Method      :  TACHO_Enable (component Capture)
**     Description :
**         This method enables the component - it starts the capture.
**         Events may be generated (<DisableEvent>/<EnableEvent>).
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/

byte TACHO_Disable(void);
/*
** ===================================================================
**     Method      :  TACHO_Disable (component Capture)
**     Description :
**         This method disables the component - it stops the capture.
**         No events will be generated.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/

byte TACHO_EnableEvent(void);
/*
** ===================================================================
**     Method      :  TACHO_EnableEvent (component Capture)
**     Description :
**         This method enables the events. This method is available
**         only if any event is selected.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/

byte TACHO_DisableEvent(void);
/*
** ===================================================================
**     Method      :  TACHO_DisableEvent (component Capture)
**     Description :
**         This method disables the events.  This method is available
**         only if any event is selected.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/

byte TACHO_Reset(void);
/*
** ===================================================================
**     Method      :  TACHO_Reset (component Capture)
**     Description :
**         This method resets the counter register (see implementation
**         note in <General Info>).
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/

byte TACHO_GetCaptureValue(TACHO_TCapturedValue *Value);
/*
** ===================================================================
**     Method      :  TACHO_GetCaptureValue (component Capture)
**     Description :
**         This method gets the last value captured by enabled timer.
**         Note: one tick of timer is
**               333.333333333333 ns in high speed mode
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Value           - A pointer to the content of the
**                           capture register
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/

void TACHO_Init(void);
/*
** ===================================================================
**     Method      :  TACHO_Init (component Capture)
**
**     Description :
**         Initializes the associated peripheral(s) and the component 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

void TACHO_Interrupt(void);
/*
** ===================================================================
**     Method      :  TACHO_Interrupt (component Capture)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes event(s) of the component.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

/* END TACHO. */

#endif
/* ifndef __TACHO_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale MCF series of microcontrollers.
**
** ###################################################################
*/
