/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : I2C.c
**     Project     : 39_22_11_IN1UP
**     Processor   : MCF52233CAF60
**     Component   : Init_I2C
**     Version     : Component 01.003, Driver 01.03, CPU db: 3.00.000
**     Compiler    : CodeWarrior MCF C Compiler
**     Date/Time   : 2026-03-10, 16:39, # CodeGen: 0
**     Abstract    :
**          This file implements the I2C (I2C) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
**     Settings    :
**          Component name                                 : I2C
**          Device                                         : I2C
**          Settings                                       : 
**            Clock setting                                : 
**              Clock divisor select value                 : divide by 3840
**              I2C frequency                              : 15.3600 kHz
**            Master/Slave mode select                     : Master
**            Transmit/Receive mode select                 : Transmit
**            Transmit acknowledge                         : yes
**            Slave address                                : 1C
**          Pins                                           : 
**            SDA pin                                      : Enabled
**              Pin                                        : SDA_CANRX_URXD2_PAS1
**              Pin signal                                 : 
**            CLK pin                                      : Enabled
**              Pin                                        : SCL_CANTX_UTXD2_PAS0
**              Pin signal                                 : 
**          Interrupts/DMA                                 : 
**            I2C interrupt/DMA                            : 
**              Interrupt                                  : INT_I2C_IIF
**              Request                                    : Enabled
**              Level                                      : 5
**              Priority                                   : 5
**              ISR Name                                   : iif
**              I2C request                                : Enabled
**              I2C request type                           : Interrupt
**          Initialization                                 : 
**            Module enable                                : yes
**            Call Init method                             : yes
**     Contents    :
**         Init - void I2C_Init(void);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file I2C.c
** @version 01.03
** @brief
**          This file implements the I2C (I2C) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
*/         
/*!
**  @addtogroup I2C_module I2C module documentation
**  @{
*/         

/* MODULE I2C. */

#include "I2C.h"
  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"


/*
** ===================================================================
**     Method      :  I2C_Init (component Init_I2C)
**     Description :
**         This method initializes registers of the I2C module
**         according to the Peripheral Initialization settings.
**         Call this method in user code to initialize the module. By
**         default, the method is called by PE automatically; see "Call
**         Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void I2C_Init(void)
{
  /* I2CR: IEN=0,IIEN=1,MSTA=1,MTX=1,TXAK=0,RSTA=0,??=0,??=0 */
  setReg8(I2CR, 0x70U);                 
  /* I2FDR: ??=0,??=0,IC=0x1F */
  setReg8(I2FDR, 0x1FU);                
  /* I2ADR: ADR=0x1C,??=0 */
  setReg8(I2ADR, 0x38U);                
  /* I2SR: ICF=1,IAAS=0,IBB=0,IAL=0,??=0,SRW=0,IIF=0,RXAK=1 */
  setReg8(I2SR, 0x81U);                 
  /* I2CR: IEN=1 */
  setReg8Bits(I2CR, 0x80U);             
}

/*
** ###################################################################
**
**  The interrupt service routine(s) must be implemented
**  by user in one of the following user modules.
**
**  If the "Generate ISR" option is enabled, Processor Expert generates
**  ISR templates in the CPU event module.
**
**  User modules:
**      main.c
**      Events.c
**
** ###################################################################
PE_ISR(iif)
{
// NOTE: The routine should include actions to clear the appropriate
//       interrupt flags.
//
}
*/


/* END I2C. */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale MCF series of microcontrollers.
**
** ###################################################################
*/
