/** ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : Vectors.c
**     Project     : 39_22_11_IN1UP
**     Processor   : MCF52233CAF60
**     Version     : Component 01.003, Driver 01.06, CPU db: 3.00.000
**     Compiler    : CodeWarrior MCF C Compiler
**     Date/Time   : 2026-03-12, 10:49, # CodeGen: 6
**     Abstract    :
**
**     Settings    :
**
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file Vectors.c                                                  
** @version 01.06
** @brief
**
*/         
/*!
**  @addtogroup Vectors_module Vectors module documentation
**  @{
*/         

#include "startcf.h"
#include "Cpu.h"
#include "RTS_UART0.h"
#include "VFDserial.h"
#include "IOUPserial.h"
#include "LED4_SYS_MON.h"
#include "LED56_COMM_WARN_MON.h"
#include "LED3_Process.h"
#include "LED12_SYS.h"
#include "CS1.h"
#include "CTS_UART0.h"
#include "DB3.h"
#include "FSYNC.h"
#include "I2C.h"
#include "LED_BOOT.h"
#include "TI2.h"
#include "TI1.h"
#include "WP.h"
#include "RC.h"
#include "LED3.h"
#include "LED2.h"
#include "SDATA.h"
#include "LEDERRCOMM.h"
#include "RTC1.h"
#include "CS0.h"
#include "TACHO.h"
#include "CLK_AN_COUNT.h"
#include "CNTR_G_AMP1.h"
#include "CNTR_G_AMP2.h"
#include "CNTR_G_AMP3.h"
#include "PIN_DRIVE_OUT.h"
#include "SM1.h"
#include "FREC_SEL0_PIN.h"
#include "FREC_SEL1_PIN.h"
#include "ADC_BAL.h"
#include "Busy.h"
#include "EInt1.h"
#include "FC322.h"
#include "FC1.h"
#include "Events.h"


  /* ISR prototype */
  typedef void (*const tIsrFunc)(void);
  
  #pragma define_section vectortable ".vectortable" far_absolute R
  
  static __declspec(vectortable) tIsrFunc _InterruptVectorTable[0xC0] = { /* Interrupt vector table */
    /* ISR name                             No. Address      Lvl Pri Name                       Description */
    (tIsrFunc)__SP_AFTER_RESET,        /* 0x00  0x00000000   -   -   ivINT_INIT_SP              used by PE */
    _startup,                          /* 0x01  0x00000004   -   -   ivINT_INIT_PC              used by PE */
    Cpu_ivINT_ACC_ERR,                 /* 0x02  0x00000008   -   -   ivINT_ACC_ERR              unused by PE */
    Cpu_ivINT_ADDR_ERR,                /* 0x03  0x0000000C   -   -   ivINT_ADDR_ERR             unused by PE */
    Cpu_ivINT_ILLEGAL_INSTR,           /* 0x04  0x00000010   -   -   ivINT_ILLEGAL_INSTR        unused by PE */
    Cpu_ivINT_DIV_ZERO,                /* 0x05  0x00000014   -   -   ivINT_DIV_ZERO             unused by PE */
    Cpu_ivReserved6,                   /* 0x06  0x00000018   -   -   ivReserved6                unused by PE */
    Cpu_ivReserved7,                   /* 0x07  0x0000001C   -   -   ivReserved7                unused by PE */
    Cpu_ivINT_PRIVILEGE_VIOL,          /* 0x08  0x00000020   -   -   ivINT_PRIVILEGE_VIOL       unused by PE */
    Cpu_ivINT_TRACE,                   /* 0x09  0x00000024   -   -   ivINT_TRACE                unused by PE */
    Cpu_ivINT_UNIMPLEMENTED_A_LINE,    /* 0x0A  0x00000028   -   -   ivINT_UNIMPLEMENTED_A_LINE unused by PE */
    Cpu_ivINT_UNIMPLEMENTED_F_LINE,    /* 0x0B  0x0000002C   -   -   ivINT_UNIMPLEMENTED_F_LINE unused by PE */
    Cpu_ivINT_DEBUG,                   /* 0x0C  0x00000030   -   -   ivINT_DEBUG                unused by PE */
    Cpu_ivReserved13,                  /* 0x0D  0x00000034   -   -   ivReserved13               unused by PE */
    Cpu_ivINT_FORMAT_ERR,              /* 0x0E  0x00000038   -   -   ivINT_FORMAT_ERR           unused by PE */
    Cpu_ivReserved15,                  /* 0x0F  0x0000003C   -   -   ivReserved15               unused by PE */
    Cpu_ivReserved16,                  /* 0x10  0x00000040   -   -   ivReserved16               unused by PE */
    Cpu_ivReserved17,                  /* 0x11  0x00000044   -   -   ivReserved17               unused by PE */
    Cpu_ivReserved18,                  /* 0x12  0x00000048   -   -   ivReserved18               unused by PE */
    Cpu_ivReserved19,                  /* 0x13  0x0000004C   -   -   ivReserved19               unused by PE */
    Cpu_ivReserved20,                  /* 0x14  0x00000050   -   -   ivReserved20               unused by PE */
    Cpu_ivReserved21,                  /* 0x15  0x00000054   -   -   ivReserved21               unused by PE */
    Cpu_ivReserved22,                  /* 0x16  0x00000058   -   -   ivReserved22               unused by PE */
    Cpu_ivReserved23,                  /* 0x17  0x0000005C   -   -   ivReserved23               unused by PE */
    Cpu_INT_SPURIOUS_INT,              /* 0x18  0x00000060   -   -   ivINT_SPURIOUS_INT         used by PE */
    Cpu_ivReserved25,                  /* 0x19  0x00000064   -   -   ivReserved25               unused by PE */
    Cpu_ivReserved26,                  /* 0x1A  0x00000068   -   -   ivReserved26               unused by PE */
    Cpu_ivReserved27,                  /* 0x1B  0x0000006C   -   -   ivReserved27               unused by PE */
    Cpu_ivReserved28,                  /* 0x1C  0x00000070   -   -   ivReserved28               unused by PE */
    Cpu_ivReserved29,                  /* 0x1D  0x00000074   -   -   ivReserved29               unused by PE */
    Cpu_ivReserved30,                  /* 0x1E  0x00000078   -   -   ivReserved30               unused by PE */
    Cpu_ivReserved31,                  /* 0x1F  0x0000007C   -   -   ivReserved31               unused by PE */
    Cpu_ivINT_TRAP0,                   /* 0x20  0x00000080   -   -   ivINT_TRAP0                unused by PE */
    Cpu_ivINT_TRAP1,                   /* 0x21  0x00000084   -   -   ivINT_TRAP1                unused by PE */
    Cpu_ivINT_TRAP2,                   /* 0x22  0x00000088   -   -   ivINT_TRAP2                unused by PE */
    Cpu_ivINT_TRAP3,                   /* 0x23  0x0000008C   -   -   ivINT_TRAP3                unused by PE */
    Cpu_ivINT_TRAP4,                   /* 0x24  0x00000090   -   -   ivINT_TRAP4                unused by PE */
    Cpu_ivINT_TRAP5,                   /* 0x25  0x00000094   -   -   ivINT_TRAP5                unused by PE */
    Cpu_ivINT_TRAP6,                   /* 0x26  0x00000098   -   -   ivINT_TRAP6                unused by PE */
    Cpu_ivINT_TRAP7,                   /* 0x27  0x0000009C   -   -   ivINT_TRAP7                unused by PE */
    Cpu_ivINT_TRAP8,                   /* 0x28  0x000000A0   -   -   ivINT_TRAP8                unused by PE */
    Cpu_ivINT_TRAP9,                   /* 0x29  0x000000A4   -   -   ivINT_TRAP9                unused by PE */
    Cpu_ivINT_TRAP10,                  /* 0x2A  0x000000A8   -   -   ivINT_TRAP10               unused by PE */
    Cpu_ivINT_TRAP11,                  /* 0x2B  0x000000AC   -   -   ivINT_TRAP11               unused by PE */
    Cpu_ivINT_TRAP12,                  /* 0x2C  0x000000B0   -   -   ivINT_TRAP12               unused by PE */
    Cpu_ivINT_TRAP13,                  /* 0x2D  0x000000B4   -   -   ivINT_TRAP13               unused by PE */
    Cpu_ivINT_TRAP14,                  /* 0x2E  0x000000B8   -   -   ivINT_TRAP14               unused by PE */
    Cpu_ivINT_TRAP15,                  /* 0x2F  0x000000BC   -   -   ivINT_TRAP15               unused by PE */
    Cpu_ivReserved48,                  /* 0x30  0x000000C0   -   -   ivReserved48               unused by PE */
    Cpu_ivReserved49,                  /* 0x31  0x000000C4   -   -   ivReserved49               unused by PE */
    Cpu_ivReserved50,                  /* 0x32  0x000000C8   -   -   ivReserved50               unused by PE */
    Cpu_ivReserved51,                  /* 0x33  0x000000CC   -   -   ivReserved51               unused by PE */
    Cpu_ivReserved52,                  /* 0x34  0x000000D0   -   -   ivReserved52               unused by PE */
    Cpu_ivReserved53,                  /* 0x35  0x000000D4   -   -   ivReserved53               unused by PE */
    Cpu_ivReserved54,                  /* 0x36  0x000000D8   -   -   ivReserved54               unused by PE */
    Cpu_ivReserved55,                  /* 0x37  0x000000DC   -   -   ivReserved55               unused by PE */
    Cpu_ivReserved56,                  /* 0x38  0x000000E0   -   -   ivReserved56               unused by PE */
    Cpu_ivReserved57,                  /* 0x39  0x000000E4   -   -   ivReserved57               unused by PE */
    Cpu_ivReserved58,                  /* 0x3A  0x000000E8   -   -   ivReserved58               unused by PE */
    Cpu_ivReserved59,                  /* 0x3B  0x000000EC   -   -   ivReserved59               unused by PE */
    Cpu_ivReserved60,                  /* 0x3C  0x000000F0   -   -   ivReserved60               unused by PE */
    Cpu_ivReserved61,                  /* 0x3D  0x000000F4   -   -   ivReserved61               unused by PE */
    Cpu_ivReserved62,                  /* 0x3E  0x000000F8   -   -   ivReserved62               unused by PE */
    Cpu_ivReserved63,                  /* 0x3F  0x000000FC   -   -   ivReserved63               unused by PE */
    Cpu_ivReserved64,                  /* 0x40  0x00000100   -   -   ivReserved64               unused by PE */
    EInt1_Interrupt,                   /* 0x41  0x00000104   1   mid   ivINT_EPORT0_EPF1          used by PE */
    Cpu_ivINT_EPORT0_EPF2,             /* 0x42  0x00000108   -   -   ivINT_EPORT0_EPF2          unused by PE */
    Cpu_ivINT_EPORT0_EPF3,             /* 0x43  0x0000010C   -   -   ivINT_EPORT0_EPF3          unused by PE */
    Cpu_ivINT_EPORT0_EPF4,             /* 0x44  0x00000110   -   -   ivINT_EPORT0_EPF4          unused by PE */
    Cpu_ivINT_EPORT0_EPF5,             /* 0x45  0x00000114   -   -   ivINT_EPORT0_EPF5          unused by PE */
    Cpu_ivINT_EPORT0_EPF6,             /* 0x46  0x00000118   -   -   ivINT_EPORT0_EPF6          unused by PE */
    Cpu_ivINT_EPORT0_EPF7,             /* 0x47  0x0000011C   -   -   ivINT_EPORT0_EPF7          unused by PE */
    Cpu_INT_SCM_SWTIInterrupt,         /* 0x48  0x00000120   0   0   ivINT_SCM_SWTI             used by PE */
    Cpu_ivINT_DMA0_DONE,               /* 0x49  0x00000124   -   -   ivINT_DMA0_DONE            unused by PE */
    Cpu_ivINT_DMA1_DONE,               /* 0x4A  0x00000128   -   -   ivINT_DMA1_DONE            unused by PE */
    Cpu_ivINT_DMA2_DONE,               /* 0x4B  0x0000012C   -   -   ivINT_DMA2_DONE            unused by PE */
    Cpu_ivINT_DMA3_DONE,               /* 0x4C  0x00000130   -   -   ivINT_DMA3_DONE            unused by PE */
    IOUPserial_Interrupt,              /* 0x4D  0x00000134   5   0   ivINT_UART0                used by PE */
    VFDserial_Interrupt,               /* 0x4E  0x00000138   1   2   ivINT_UART1                used by PE */
    Cpu_ivINT_UART2,                   /* 0x4F  0x0000013C   -   -   ivINT_UART2                unused by PE */
    Cpu_ivReserved80,                  /* 0x50  0x00000140   -   -   ivReserved80               unused by PE */
    iif,                               /* 0x51  0x00000144   5   5   ivINT_I2C_IIF              used by PE */
    Cpu_ivINT_QSPI,                    /* 0x52  0x00000148   -   -   ivINT_QSPI                 unused by PE */
    Cpu_ivINT_DTIM0,                   /* 0x53  0x0000014C   -   -   ivINT_DTIM0                unused by PE */
    Cpu_ivINT_DTIM1,                   /* 0x54  0x00000150   -   -   ivINT_DTIM1                unused by PE */
    Cpu_ivINT_DTIM2,                   /* 0x55  0x00000154   -   -   ivINT_DTIM2                unused by PE */
    Cpu_ivINT_DTIM3,                   /* 0x56  0x00000158   -   -   ivINT_DTIM3                unused by PE */
    Cpu_ivINT_FEC_X_INTF,              /* 0x57  0x0000015C   -   -   ivINT_FEC_X_INTF           unused by PE */
    Cpu_ivINT_FEC_X_INTB,              /* 0x58  0x00000160   -   -   ivINT_FEC_X_INTB           unused by PE */
    Cpu_ivINT_FEC_UN,                  /* 0x59  0x00000164   -   -   ivINT_FEC_UN               unused by PE */
    Cpu_ivINT_FEC_RL,                  /* 0x5A  0x00000168   -   -   ivINT_FEC_RL               unused by PE */
    Cpu_ivINT_FEC_R_INTF,              /* 0x5B  0x0000016C   -   -   ivINT_FEC_R_INTF           unused by PE */
    Cpu_ivINT_FEC_R_INTB,              /* 0x5C  0x00000170   -   -   ivINT_FEC_R_INTB           unused by PE */
    Cpu_ivINT_FEC_MII,                 /* 0x5D  0x00000174   -   -   ivINT_FEC_MII              unused by PE */
    Cpu_ivINT_FEC_LC,                  /* 0x5E  0x00000178   -   -   ivINT_FEC_LC               unused by PE */
    Cpu_ivINT_FEC_HBERR,               /* 0x5F  0x0000017C   -   -   ivINT_FEC_HBERR            unused by PE */
    Cpu_ivINT_FEC_GRA,                 /* 0x60  0x00000180   -   -   ivINT_FEC_GRA              unused by PE */
    Cpu_ivINT_FEC_EBERR,               /* 0x61  0x00000184   -   -   ivINT_FEC_EBERR            unused by PE */
    Cpu_ivINT_FEC_BABT,                /* 0x62  0x00000188   -   -   ivINT_FEC_BABT             unused by PE */
    Cpu_ivINT_FEC_BABR,                /* 0x63  0x0000018C   -   -   ivINT_FEC_BABR             unused by PE */
    Cpu_ivReserved100,                 /* 0x64  0x00000190   -   -   ivReserved100              unused by PE */
    Cpu_ivReserved101,                 /* 0x65  0x00000194   -   -   ivReserved101              unused by PE */
    Cpu_ivReserved102,                 /* 0x66  0x00000198   -   -   ivReserved102              unused by PE */
    Cpu_ivReserved103,                 /* 0x67  0x0000019C   -   -   ivReserved103              unused by PE */
    Cpu_ivReserved104,                 /* 0x68  0x000001A0   -   -   ivReserved104              unused by PE */
    CLK_AN_COUNT_InterruptOvf,         /* 0x69  0x000001A4   1   0   ivINT_GPT_TOF              used by PE */
    Cpu_ivINT_GPT_PAIF,                /* 0x6A  0x000001A8   -   -   ivINT_GPT_PAIF             unused by PE */
    Cpu_ivINT_GPT_PAOVF,               /* 0x6B  0x000001AC   -   -   ivINT_GPT_PAOVF            unused by PE */
    TI2_Interrupt,                     /* 0x6C  0x000001B0   1   2   ivINT_GPT_C0F              used by PE */
    TI1_Interrupt,                     /* 0x6D  0x000001B4   5   7   ivINT_GPT_C1F              used by PE */
    TACHO_Interrupt,                   /* 0x6E  0x000001B8   6   1   ivINT_GPT_C2F              used by PE */
    CLK_AN_COUNT_Interrupt,            /* 0x6F  0x000001BC   1   1   ivINT_GPT_C3F              used by PE */
    Cpu_ivINT_PMM_LVDF,                /* 0x70  0x000001C0   -   -   ivINT_PMM_LVDF             unused by PE */
    ADC_BAL_InterruptCC,               /* 0x71  0x000001C4   1   5   ivINT_ADC_ADCA             used by PE */
    Cpu_ivINT_ADC_ADCB,                /* 0x72  0x000001C8   -   -   ivINT_ADC_ADCB             unused by PE */
    Cpu_ivINT_ADC_ADCINT,              /* 0x73  0x000001CC   1   4   ivINT_ADC_ADCINT           unused by PE */
    Cpu_ivINT_PWM,                     /* 0x74  0x000001D0   -   -   ivINT_PWM                  unused by PE */
    Cpu_ivINT_RNGA,                    /* 0x75  0x000001D4   -   -   ivINT_RNGA                 unused by PE */
    Cpu_ivReserved118,                 /* 0x76  0x000001D8   -   -   ivReserved118              unused by PE */
    FC322_Interrupt,                   /* 0x77  0x000001DC   4   2   ivINT_PIT0_PIF             used by PE */
    Cpu_ivINT_PIT1_PIF,                /* 0x78  0x000001E0   -   -   ivINT_PIT1_PIF             unused by PE */
    Cpu_ivReserved121,                 /* 0x79  0x000001E4   -   -   ivReserved121              unused by PE */
    Cpu_ivReserved122,                 /* 0x7A  0x000001E8   -   -   ivReserved122              unused by PE */
    Cpu_ivINT_CFM_CBEIF,               /* 0x7B  0x000001EC   -   -   ivINT_CFM_CBEIF            unused by PE */
    Cpu_ivINT_CFM_CCIF,                /* 0x7C  0x000001F0   -   -   ivINT_CFM_CCIF             unused by PE */
    Cpu_ivINT_CFM_PVIF,                /* 0x7D  0x000001F4   -   -   ivINT_CFM_PVIF             unused by PE */
    Cpu_ivINT_CFM_AEIF,                /* 0x7E  0x000001F8   -   -   ivINT_CFM_AEIF             unused by PE */
    RTC1_Interrupt,                    /* 0x7F  0x000001FC   6   3   ivINT_RTC                  used by PE */
    Cpu_ivReserved128,                 /* 0x80  0x00000200   -   -   ivReserved128              unused by PE */
    Cpu_ivReserved129,                 /* 0x81  0x00000204   -   -   ivReserved129              unused by PE */
    Cpu_ivReserved130,                 /* 0x82  0x00000208   -   -   ivReserved130              unused by PE */
    Cpu_ivReserved131,                 /* 0x83  0x0000020C   -   -   ivReserved131              unused by PE */
    Cpu_ivReserved132,                 /* 0x84  0x00000210   -   -   ivReserved132              unused by PE */
    Cpu_ivReserved133,                 /* 0x85  0x00000214   -   -   ivReserved133              unused by PE */
    Cpu_ivReserved134,                 /* 0x86  0x00000218   -   -   ivReserved134              unused by PE */
    Cpu_ivReserved135,                 /* 0x87  0x0000021C   -   -   ivReserved135              unused by PE */
    Cpu_ivINT_FLEXCAN_BUF0I,           /* 0x88  0x00000220   -   -   ivINT_FLEXCAN_BUF0I        unused by PE */
    Cpu_ivINT_FLEXCAN_BUF1I,           /* 0x89  0x00000224   -   -   ivINT_FLEXCAN_BUF1I        unused by PE */
    Cpu_ivINT_FLEXCAN_BUF2I,           /* 0x8A  0x00000228   -   -   ivINT_FLEXCAN_BUF2I        unused by PE */
    Cpu_ivINT_FLEXCAN_BUF3I,           /* 0x8B  0x0000022C   -   -   ivINT_FLEXCAN_BUF3I        unused by PE */
    Cpu_ivINT_FLEXCAN_BUF4I,           /* 0x8C  0x00000230   -   -   ivINT_FLEXCAN_BUF4I        unused by PE */
    Cpu_ivINT_FLEXCAN_BUF5I,           /* 0x8D  0x00000234   -   -   ivINT_FLEXCAN_BUF5I        unused by PE */
    Cpu_ivINT_FLEXCAN_BUF6I,           /* 0x8E  0x00000238   -   -   ivINT_FLEXCAN_BUF6I        unused by PE */
    Cpu_ivINT_FLEXCAN_BUF7I,           /* 0x8F  0x0000023C   -   -   ivINT_FLEXCAN_BUF7I        unused by PE */
    Cpu_ivINT_FLEXCAN_BUF8I,           /* 0x90  0x00000240   -   -   ivINT_FLEXCAN_BUF8I        unused by PE */
    Cpu_ivINT_FLEXCAN_BUF9I,           /* 0x91  0x00000244   -   -   ivINT_FLEXCAN_BUF9I        unused by PE */
    Cpu_ivINT_FLEXCAN_BUF10I,          /* 0x92  0x00000248   -   -   ivINT_FLEXCAN_BUF10I       unused by PE */
    Cpu_ivINT_FLEXCAN_BUF11I,          /* 0x93  0x0000024C   -   -   ivINT_FLEXCAN_BUF11I       unused by PE */
    Cpu_ivINT_FLEXCAN_BUF12I,          /* 0x94  0x00000250   -   -   ivINT_FLEXCAN_BUF12I       unused by PE */
    Cpu_ivINT_FLEXCAN_BUF13I,          /* 0x95  0x00000254   -   -   ivINT_FLEXCAN_BUF13I       unused by PE */
    Cpu_ivINT_FLEXCAN_BUF14I,          /* 0x96  0x00000258   -   -   ivINT_FLEXCAN_BUF14I       unused by PE */
    Cpu_ivINT_FLEXCAN_BUF15I,          /* 0x97  0x0000025C   -   -   ivINT_FLEXCAN_BUF15I       unused by PE */
    Cpu_ivINT_FLEXCAN_ERR_INT,         /* 0x98  0x00000260   -   -   ivINT_FLEXCAN_ERR_INT      unused by PE */
    Cpu_ivINT_FLEXCAN_BOFF_INT,        /* 0x99  0x00000264   -   -   ivINT_FLEXCAN_BOFF_INT     unused by PE */
    Cpu_ivReserved154,                 /* 0x9A  0x00000268   -   -   ivReserved154              unused by PE */
    Cpu_ivReserved155,                 /* 0x9B  0x0000026C   -   -   ivReserved155              unused by PE */
    Cpu_ivReserved156,                 /* 0x9C  0x00000270   -   -   ivReserved156              unused by PE */
    Cpu_ivReserved157,                 /* 0x9D  0x00000274   -   -   ivReserved157              unused by PE */
    Cpu_ivReserved158,                 /* 0x9E  0x00000278   -   -   ivReserved158              unused by PE */
    Cpu_ivReserved159,                 /* 0x9F  0x0000027C   -   -   ivReserved159              unused by PE */
    Cpu_ivINT_EPORT1_EPF0,             /* 0xA0  0x00000280   -   -   ivINT_EPORT1_EPF0          unused by PE */
    Cpu_ivINT_EPORT1_EPF1,             /* 0xA1  0x00000284   -   -   ivINT_EPORT1_EPF1          unused by PE */
    Cpu_ivINT_EPORT1_EPF2,             /* 0xA2  0x00000288   -   -   ivINT_EPORT1_EPF2          unused by PE */
    Busy_Interrupt,                    /* 0xA3  0x0000028C   4   3   ivINT_EPORT1_EPF3          used by PE */
    Cpu_ivINT_EPORT1_EPF4,             /* 0xA4  0x00000290   -   -   ivINT_EPORT1_EPF4          unused by PE */
    Cpu_ivINT_EPORT1_EPF5,             /* 0xA5  0x00000294   -   -   ivINT_EPORT1_EPF5          unused by PE */
    Cpu_ivINT_EPORT1_EPF6,             /* 0xA6  0x00000298   -   -   ivINT_EPORT1_EPF6          unused by PE */
    Cpu_ivINT_EPORT1_EPF7,             /* 0xA7  0x0000029C   -   -   ivINT_EPORT1_EPF7          unused by PE */
    Cpu_ivReserved168,                 /* 0xA8  0x000002A0   -   -   ivReserved168              unused by PE */
    Cpu_ivReserved169,                 /* 0xA9  0x000002A4   -   -   ivReserved169              unused by PE */
    Cpu_ivReserved170,                 /* 0xAA  0x000002A8   -   -   ivReserved170              unused by PE */
    Cpu_ivReserved171,                 /* 0xAB  0x000002AC   -   -   ivReserved171              unused by PE */
    Cpu_ivReserved172,                 /* 0xAC  0x000002B0   -   -   ivReserved172              unused by PE */
    Cpu_ivReserved173,                 /* 0xAD  0x000002B4   -   -   ivReserved173              unused by PE */
    Cpu_ivReserved174,                 /* 0xAE  0x000002B8   -   -   ivReserved174              unused by PE */
    Cpu_ivReserved175,                 /* 0xAF  0x000002BC   -   -   ivReserved175              unused by PE */
    Cpu_ivReserved176,                 /* 0xB0  0x000002C0   -   -   ivReserved176              unused by PE */
    Cpu_ivReserved177,                 /* 0xB1  0x000002C4   -   -   ivReserved177              unused by PE */
    Cpu_ivReserved178,                 /* 0xB2  0x000002C8   -   -   ivReserved178              unused by PE */
    Cpu_ivReserved179,                 /* 0xB3  0x000002CC   -   -   ivReserved179              unused by PE */
    Cpu_ivReserved180,                 /* 0xB4  0x000002D0   -   -   ivReserved180              unused by PE */
    Cpu_ivReserved181,                 /* 0xB5  0x000002D4   -   -   ivReserved181              unused by PE */
    Cpu_ivReserved182,                 /* 0xB6  0x000002D8   -   -   ivReserved182              unused by PE */
    Cpu_ivReserved183,                 /* 0xB7  0x000002DC   -   -   ivReserved183              unused by PE */
    Cpu_ivReserved184,                 /* 0xB8  0x000002E0   -   -   ivReserved184              unused by PE */
    Cpu_ivReserved185,                 /* 0xB9  0x000002E4   -   -   ivReserved185              unused by PE */
    Cpu_ivReserved186,                 /* 0xBA  0x000002E8   -   -   ivReserved186              unused by PE */
    Cpu_ivReserved187,                 /* 0xBB  0x000002EC   -   -   ivReserved187              unused by PE */
    Cpu_ivReserved188,                 /* 0xBC  0x000002F0   -   -   ivReserved188              unused by PE */
    Cpu_ivReserved189,                 /* 0xBD  0x000002F4   -   -   ivReserved189              unused by PE */
    Cpu_ivReserved190,                 /* 0xBE  0x000002F8   -   -   ivReserved190              unused by PE */
    Cpu_ivReserved191                  /* 0xBF  0x000002FC   -   -   ivReserved191              unused by PE */
  };
  
  /* CFM init */
  
  #define CFM_KEY_UPPER   0x00
  #define CFM_KEY_LOWER   0x00
  #define CFM_CFMPROT     0x00
  #define CFM_CFMSACC     0x00
  #define CFM_CFMDACC     0x00
  #define CFM_CFMSEC      0x00
  
  #pragma define_section cfmconfig ".cfmconfig"  far_absolute R
  #pragma explicit_zero_data on
  
  __declspec(cfmconfig)  unsigned long _cfm[0x06] = {
    CFM_KEY_UPPER,    /* 0x00000400 */
    CFM_KEY_LOWER,    /* 0x00000404 */
    CFM_CFMPROT,      /* 0x00000408 */
    CFM_CFMSACC,      /* 0x0000040C */
    CFM_CFMDACC,      /* 0x00000410 */
    CFM_CFMSEC        /* 0x00000414 */
  };
  

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale MCF series of microcontrollers.
**
** ###################################################################
*/
