/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : VFDserial.c
**     Project     : 39_22_11_IN1UP
**     Processor   : MCF52233CAF60
**     Component   : AsynchroSerial
**     Version     : Component 02.611, Driver 01.02, CPU db: 3.00.000
**     Compiler    : CodeWarrior MCF C Compiler
**     Date/Time   : 2026-03-10, 16:39, # CodeGen: 0
**     Abstract    :
**         This component "AsynchroSerial" implements an asynchronous serial
**         communication. The component supports different settings of
**         parity, word width, stop-bit and communication speed,
**         user can select interrupt or polling handler.
**         Communication speed can be changed also in runtime.
**         The component requires one on-chip asynchronous serial channel.
**     Settings    :
**         Serial channel              : UART1
**
**         Protocol
**             Init baud rate          : 19200baud
**             Width                   : 8 bits
**             Stop bits               : 1.000
**             Parity                  : none
**             Breaks                  : Disabled
**             Input buffer size       : 200
**             Output buffer size      : 900
**
**         Registers
**             Input buffer            : URB1      [0x024C]
**             Output buffer           : UTB1      [0x024C]
**             Control register        : UMR11     [0x0240]
**             Mode register           : UMR21     [0x0240]
**             Baud setting reg.       : UCSR1     [0x0244]
**
**         Input interrupt
**             Vector name             : INT_UART1
**             Priority                : 220
**
**         Output interrupt
**             Vector name             : INT_UART1
**             Priority                : 220
**
**         Used pins:
**         ----------------------------------------------------------
**           Function | On package           |    Name
**         ----------------------------------------------------------
**            Input   |     23               |  URXD1_FEC_TXD0_PUB1
**            Output  |     24               |  UTXD1_FEC_COL_PUB0
**         ----------------------------------------------------------
**
**
**
**     Contents    :
**         RecvChar        - byte VFDserial_RecvChar(VFDserial_TComData *Chr);
**         SendChar        - byte VFDserial_SendChar(VFDserial_TComData Chr);
**         RecvBlock       - byte VFDserial_RecvBlock(VFDserial_TComData *Ptr, word Size, word *Rcv);
**         SendBlock       - byte VFDserial_SendBlock(VFDserial_TComData *Ptr, word Size, word *Snd);
**         ClearRxBuf      - byte VFDserial_ClearRxBuf(void);
**         ClearTxBuf      - byte VFDserial_ClearTxBuf(void);
**         GetCharsInRxBuf - word VFDserial_GetCharsInRxBuf(void);
**         CharsInTxBuf    - byte VFDserial_CharsInTxBuf(word *Chr);
**         GetCharsInTxBuf - word VFDserial_GetCharsInTxBuf(void);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file VFDserial.c
** @version 01.02
** @brief
**         This component "AsynchroSerial" implements an asynchronous serial
**         communication. The component supports different settings of
**         parity, word width, stop-bit and communication speed,
**         user can select interrupt or polling handler.
**         Communication speed can be changed also in runtime.
**         The component requires one on-chip asynchronous serial channel.
*/         
/*!
**  @addtogroup VFDserial_module VFDserial module documentation
**  @{
*/         

/* MODULE VFDserial. */

#include "VFDserial.h"
#include "Events.h"


#define OVERRUN_ERR      0x01          /* Overrun error flag bit    */
#define FRAMING_ERR      0x02          /* Framing error flag bit    */
#define PARITY_ERR       0x04          /* Parity error flag bit     */
#define CHAR_IN_RX       0x08          /* Char is in RX buffer      */
#define FULL_TX          0x10          /* Full transmit buffer      */
#define RUNINT_FROM_TX   0x20          /* Interrupt is in progress  */
#define FULL_RX          0x40          /* Full receive buffer       */
#define ENABLED_TX_INT   0x80          /* TX interrupt enabled      */
#define BREAK_ERR        0x0200        /* Break detect              */
#define COMMON_ERR       0x0800        /* Common error of RX       */

static volatile word SerFlag;          /* Flags for serial communication */
                                       /* Bits: 0 - OverRun error */
                                       /*       1 - Framing error */
                                       /*       2 - Parity error */
                                       /*       3 - Char in RX buffer */
                                       /*       4 - Full TX buffer */
                                       /*       5 - Running int from TX */
                                       /*       6 - Full RX buffer */
                                       /*       7 - TX interrupt enabled */
                                       /*       8 - Unused  */
                                       /*       9 - Break detected  */
                                       /*      10 - Unused */
                                       /*      11 - Unused */
volatile word VFDserial_InpLen;        /* Length of input buffer's content */
static volatile VFDserial_TComData *InpPtrR; /* Pointer for reading from input buffer */
static volatile VFDserial_TComData *InpPtrW; /* Pointer for writing to input buffer */
static volatile VFDserial_TComData InpBuffer[VFDserial_INP_BUF_SIZE]; /* Input buffer for serial commmunication */
volatile word VFDserial_OutLen;        /* Length of output bufer's content */
static volatile VFDserial_TComData *OutPtrR; /* Pointer for reading from output buffer */
static volatile VFDserial_TComData *OutPtrW; /* Pointer for writing to output buffer */
static volatile VFDserial_TComData OutBuffer[VFDserial_OUT_BUF_SIZE]; /* Output buffer for serial commmunication */

/*
** ===================================================================
**     Method      :  HWEnDi (component AsynchroSerial)
**
**     Description :
**         Enables or disables the peripheral(s) associated with the 
**         component. The method is called automatically as a part of the 
**         Enable and Disable methods and several internal methods.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void HWEnDi(void)
{
  setReg8(UCR1, (UCR1_TC0_BITMASK | UCR1_RC0_BITMASK)); /* Enable receiver and transmitter */
  setReg8(UIMR1, 0x02);                /* Enable receiver interrupt */
}

/*
** ===================================================================
**     Method      :  VFDserial_RecvChar (component AsynchroSerial)
**     Description :
**         If any data is received, this method returns one character,
**         otherwise it returns an error code (it does not wait for
**         data). This method is enabled only if the receiver property
**         is enabled.
**         [Note:] Because the preferred method to handle error and
**         break exception in the interrupt mode is to use events
**         <OnError> and <OnBreak> the return value ERR_RXEMPTY has
**         higher priority than other error codes. As a consequence the
**         information about an exception in interrupt mode is returned
**         only if there is a valid character ready to be read.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Chr             - Pointer to a received character
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_RXEMPTY - No data in receiver
**                           ERR_BREAK - Break character is detected
**                           (only when the <Interrupt service> property
**                           is disabled and the <Break signal> property
**                           is enabled)
**                           ERR_COMMON - common error occurred (the
**                           <GetError> method can be used for error
**                           specification)
** ===================================================================
*/
byte VFDserial_RecvChar(VFDserial_TComData *Chr)
{
  register byte Result = ERR_OK;       /* Return error code */

  if (VFDserial_InpLen > 0x00) {       /* Is number of received chars greater than 0? */
    EnterCritical();                   /* Disable global interrupts */
    VFDserial_InpLen--;                /* Decrease number of received chars */
    *Chr = *(InpPtrR++);               /* Received char */
    if (InpPtrR >= (InpBuffer + VFDserial_INP_BUF_SIZE)) { /* Is the pointer out of the receive buffer? */
      InpPtrR = InpBuffer;             /* Set pointer to the first item into the receive buffer */
    }
    Result = (byte)((SerFlag & (OVERRUN_ERR | COMMON_ERR | FULL_RX))? ERR_COMMON : ERR_OK);
    SerFlag &= ~(OVERRUN_ERR | COMMON_ERR | FULL_RX | CHAR_IN_RX); /* Clear all errors in the status variable */
    ExitCritical();                    /* Enable global interrupts */
  } else {
    return ERR_RXEMPTY;                /* Receiver is empty */
  }
  return Result;                       /* Return error code */
}

/*
** ===================================================================
**     Method      :  VFDserial_SendChar (component AsynchroSerial)
**     Description :
**         Sends one character to the channel. If the component is
**         temporarily disabled (Disable method) SendChar method only
**         stores data into an output buffer. In case of a zero output
**         buffer size, only one character can be stored. Enabling the
**         component (Enable method) starts the transmission of the
**         stored data. This method is available only if the
**         transmitter property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Chr             - Character to send
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_TXFULL - Transmitter is full
** ===================================================================
*/
byte VFDserial_SendChar(VFDserial_TComData Chr)
{
  if (VFDserial_OutLen == VFDserial_OUT_BUF_SIZE) { /* Is number of chars in buffer is the same as a size of the transmit buffer */
    return ERR_TXFULL;                 /* If yes then error */
  }
  EnterCritical();                     /* Disable global interrupts */
  VFDserial_OutLen++;                  /* Increase number of bytes in the transmit buffer */
  *(OutPtrW++) = Chr;                  /* Store char to buffer */
  if (OutPtrW >= (OutBuffer + VFDserial_OUT_BUF_SIZE)) { /* Is the pointer out of the transmit buffer */
    OutPtrW = OutBuffer;               /* Set pointer to first item in the transmit buffer */
  }
  SerFlag |= ENABLED_TX_INT;           /* Set the flag ENABLED_TX_INT */
  setReg8(UIMR1, 0x03);                /* Enable transmit interrupt */
  ExitCritical();                      /* Enable global interrupts */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  VFDserial_RecvBlock (component AsynchroSerial)
**     Description :
**         If any data is received, this method returns the block of
**         the data and its length (and incidental error), otherwise it
**         returns an error code (it does not wait for data).
**         This method is available only if non-zero length of the
**         input buffer is defined and the receiver property is enabled.
**         If less than requested number of characters is received only
**         the available data is copied from the receive buffer to the
**         user specified destination. The value ERR_EXEMPTY is
**         returned and the value of variable pointed by the Rcv
**         parameter is set to the number of received characters.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Ptr             - Pointer to the block of received data
**         Size            - Size of the block
**       * Rcv             - Pointer to real number of the received data
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_RXEMPTY - The receive buffer didn't
**                           contain the requested number of data. Only
**                           available data has been returned.
**                           ERR_COMMON - common error occurred (the
**                           GetError method can be used for error
**                           specification)
** ===================================================================
*/
byte VFDserial_RecvBlock(VFDserial_TComData *Ptr,word Size,word *Rcv)
{
  register word count;                 /* Number of received chars */
  register byte result = ERR_OK;       /* Last error */

  for(count = 0; count < Size; count++) {
    switch ( VFDserial_RecvChar(Ptr++)) {
    case ERR_RXEMPTY:
      if (result == ERR_OK) {
        result = ERR_RXEMPTY;
      }
     *Rcv = count;                     /* Return number of received chars */
      return result;
      break;
    case ERR_COMMON:
      result = ERR_COMMON;             /* Return the info that an error was detected */
      break;
    default:
      break;
    }
  }
  *Rcv = count;                        /* Return number of received chars */
  return result;                       /* Return last error code */
}

/*
** ===================================================================
**     Method      :  VFDserial_SendBlock (component AsynchroSerial)
**     Description :
**         Sends a block of characters to the channel.
**         This method is available only if non-zero length of the
**         output buffer is defined and the transmitter property is
**         enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Ptr             - Pointer to the block of data to send
**         Size            - Size of the block
**       * Snd             - Pointer to number of data that are sent
**                           (moved to buffer)
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_TXFULL - It was not possible to send
**                           requested number of bytes
** ===================================================================
*/
byte VFDserial_SendBlock(VFDserial_TComData *Ptr,word Size,word *Snd)
{
  register word count;                 /* Number of sent chars */
  register byte result = ERR_OK;       /* Last error */

  for (count = 0x00; count < Size; count++) {
    result = VFDserial_SendChar(*Ptr++);
    if (result != ERR_OK) {            /* Sending given number of chars */
      *Snd = count;                    /* Return number of sent chars */
      return result;                   /* Return last error */
    }
  }
  *Snd = count;                        /* Return number of sended chars */
  return result;                       /* Return error code */
}

/*
** ===================================================================
**     Method      :  VFDserial_ClearRxBuf (component AsynchroSerial)
**     Description :
**         Clears the receive buffer.
**         This method is available only if non-zero length of the
**         input buffer is defined and the receiver property is enabled.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte VFDserial_ClearRxBuf(void)
{
  EnterCritical();                     /* Disable global interrupts */
  VFDserial_InpLen = 0x00;             /* Set number of chars in the transmit buffer to 0 */
  InpPtrR = InpPtrW = InpBuffer;       /* Set pointers on the first item in the transmit buffer */
  ExitCritical();                      /* Enable global interrupts */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  VFDserial_ClearTxBuf (component AsynchroSerial)
**     Description :
**         Clears the transmit buffer.
**         This method is available only if non-zero length of the
**         output buffer is defined and the receiver property is
**         enabled.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte VFDserial_ClearTxBuf(void)
{
  EnterCritical();                     /* Disable global interrupts */
  VFDserial_OutLen = 0x00;             /* Set number of chars in the receive buffer to 0 */
  OutPtrR = OutPtrW = OutBuffer;       /* Set pointers on the first item in the receive buffer */
  ExitCritical();                      /* Enable global interrupts */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  VFDserial_GetCharsInRxBuf (component AsynchroSerial)
**     Description :
**         Returns the number of characters in the input buffer. This
**         method is available only if the receiver property is enabled.
**     Parameters  : None
**     Returns     :
**         ---             - The number of characters in the input
**                           buffer.
** ===================================================================
*/
word VFDserial_GetCharsInRxBuf(void)
{
  return VFDserial_InpLen;             /* Return number of chars in receive buffer */
}

/*
** ===================================================================
**     Method      :  VFDserial_CharsInTxBuf (component AsynchroSerial)
**     Description :
**         Returns the number of characters in the output buffer. This
**         method is available only if the transmitter property is
**         enabled.
**         [deprecated method]
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Chr             - Pointer to the number of characters in the
**                           output buffer
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte VFDserial_CharsInTxBuf(word *Chr)
{
  *Chr = VFDserial_OutLen;             /* Return number of chars in transmit buffer */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  VFDserial_GetCharsInTxBuf (component AsynchroSerial)
**     Description :
**         Returns the number of characters in the output buffer. This
**         method is available only if the transmitter property is
**         enabled.
**     Parameters  : None
**     Returns     :
**         ---             - The number of characters in the output
**                           buffer.
** ===================================================================
*/
word VFDserial_GetCharsInTxBuf(void)
{
  return VFDserial_OutLen;             /* Return number of chars in the transmitter buffer */
}

/*
** ===================================================================
**     Method      :  VFDserial_InterruptRx (component AsynchroSerial)
**
**     Description :
**         The method services the receive interrupt of the selected 
**         peripheral(s) and eventually invokes the component's event(s).
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
#define ON_ERROR    1
#define ON_FULL_RX  2
#define ON_RX_CHAR  4
static void VFDserial_InterruptRx(void)
{
  register VFDserial_TComData Data;    /* Temporary variable for data */
  register byte OnFlags = 0x00;        /* Temporary variable for flags */

  Data = (VFDserial_TComData)getReg8(URB1); /* Read data from the receiver */
  if (VFDserial_InpLen < VFDserial_INP_BUF_SIZE) { /* Is number of bytes in the receive buffer lower than size of buffer? */
    VFDserial_InpLen++;                /* Increse number of chars in the receive buffer */
    *(InpPtrW++) = Data;               /* Save received char to the receive buffer */
    if (InpPtrW >= (InpBuffer + VFDserial_INP_BUF_SIZE)) { /* Is the pointer out of the receive buffer? */
      InpPtrW = InpBuffer;             /* Set pointer on the first item into the receive buffer */
    }
    OnFlags |= ON_RX_CHAR;             /* Set flag "OnRXChar" */
    if (VFDserial_InpLen == VFDserial_INP_BUF_SIZE) { /* Is number of bytes in the receive buffer equal as a size of buffer? */
      OnFlags |= ON_FULL_RX;           /* If yes then set flag "OnFullRxBuff" */
    }
  } else {
    SerFlag |= FULL_RX;                /* If yes then set flag buffer overflow */
    OnFlags |= ON_ERROR;               /* Set flag "OnError" */
  }
  if (OnFlags & ON_ERROR) {            /* Is error flag set? */
    VFDserial_OnError();               /* If yes then invoke user event */
  } else {
    if (OnFlags & ON_RX_CHAR) {        /* Is OnRxChar flag set? */
      VFDserial_OnRxChar();            /* If yes then invoke user event */
    }
    if (OnFlags & ON_FULL_RX) {        /* Is OnFullRxBuf flag set? */
      VFDserial_OnFullRxBuf();         /* If yes then invoke user event */
    }
  }
}

/*
** ===================================================================
**     Method      :  VFDserial_InterruptTx (component AsynchroSerial)
**
**     Description :
**         The method services the receive interrupt of the selected 
**         peripheral(s) and eventually invokes the component's event(s).
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
#define ON_FREE_TX  1
#define ON_TX_CHAR  2
static void VFDserial_InterruptTx(void)
{
  register byte OnFlags = 0x00;        /* Temporary variable for flags */

  if (SerFlag & RUNINT_FROM_TX) {      /* Is flag "running int from TX" set? */
    OnFlags |= ON_TX_CHAR;             /* Set flag "OnTxChar" */
  }
  SerFlag &= ~RUNINT_FROM_TX;          /* Reset flag "running int from TX" */
  if (VFDserial_OutLen) {              /* Is number of bytes in the transmit buffer greater then 0? */
    VFDserial_OutLen--;                /* Decrease number of chars in the transmit buffer */
    SerFlag |= RUNINT_FROM_TX;         /* Set flag "running int from TX"? */
    setReg8(UTB1, (VFDserial_TComData)*(OutPtrR++)); /* Store char to transmitter register */
    if (OutPtrR >= (OutBuffer + VFDserial_OUT_BUF_SIZE)) { /* Is the pointer out of the transmit buffer? */
      OutPtrR = OutBuffer;             /* Set pointer on the first item into the transmit buffer */
    }
  } else {
    OnFlags |= ON_FREE_TX;             /* Set flag "OnFreeTxBuf" */
    SerFlag &= ~ENABLED_TX_INT;        /* Clear the flag ENABLED_TX_INT */
    setReg8(UIMR1, 0x02);              /* Disable transmit interrupt */
  }
  if (OnFlags & ON_TX_CHAR) {          /* Is flag "OnTxChar" set? */
    VFDserial_OnTxChar();              /* If yes then invoke user event */
  }
  if (OnFlags & ON_FREE_TX) {          /* Is flag "OnFreeTxBuf" set? */
    VFDserial_OnFreeTxBuf();           /* If yes then invoke user event */
  }
}

/*
** ===================================================================
**     Method      :  VFDserial_Interrupt (component AsynchroSerial)
**
**     Description :
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
__declspec(interrupt) void VFDserial_Interrupt(void)
{
  register word StatReg = getReg8(USR1); /* Read status register */

  if (StatReg & (USR1_RB_BITMASK | USR1_OE_BITMASK | USR1_FE_BITMASK | USR1_PE_BITMASK)) { /* Is any error flag set? */
    setReg8(UCR1, 0x40);               /* Reset error request flags */
    if (StatReg & USR1_RB_BITMASK) {   /* Is break detected? */
      SerFlag |= FRAMING_ERR;          /* If yes then set the flag */
    }
    if (StatReg & (USR1_OE_BITMASK | USR1_FE_BITMASK | USR1_PE_BITMASK)) { /* Is an error detected? */
      SerFlag |= COMMON_ERR;           /* If yes then set an internal flag */
    }
    (void)getReg8(URB1);               /* Dummy read of data register - clear RXRDY bit */
    StatReg &= ~USR1_RXRDY_BITMASK;    /* Clear the receive data flag to discard the errorneous data */
    VFDserial_OnError();               /* If yes then invoke user event */
  }
  if (StatReg & USR1_RXRDY_BITMASK) {  /* Is the receiver interrupt flag set? */
    VFDserial_InterruptRx();           /* If yes, then invoke the internal service routine. This routine is inlined. */
  }
  if (SerFlag & ENABLED_TX_INT) {      /* Is the transmitter interrupt enabled? */
    if (StatReg & USR1_TXRDY_BITMASK) { /* Is the transmitter ready? */
      VFDserial_InterruptTx();         /* If yes, then invoke the internal service routine. This routine is inlined. */
    }
  }
}

/*
** ===================================================================
**     Method      :  VFDserial_Init (component AsynchroSerial)
**
**     Description :
**         Initializes the associated peripheral(s) and the component 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void VFDserial_Init(void)
{
  SerFlag = 0x00;                      /* Reset flags */
  /* UCR1: ??=0,MISC=3,TC=0,RC=0 */
  setReg8(UCR1, 0x30U);                /* Reset UART transmitter */ 
  /* UCR1: ??=0,MISC=2,TC=0,RC=0 */
  setReg8(UCR1, 0x20U);                /* Reset UART receiver */ 
  /* UMR11: RXRTS=0,RXIRQ=0,ERR=0,PM=2,PT=0,BC=3 */
  setReg8(UMR11, 0x13U);               /*  Set the UMR1 register */ 
  /* UMR21: CM=0,TXRTS=0,TXCTS=0,SB=7 */
  setReg8(UMR21, 0x07U);               /*  Set the UMR2 register */ 
  /* UCSR1: RCS=0x0D,TCS=0x0D */
  setReg8(UCSR1, 0xDDU);                
  VFDserial_InpLen = 0x00;             /* No char in the receive buffer */
  InpPtrW = InpPtrR = InpBuffer;       /* Set pointer on the first item in the receive buffer */
  VFDserial_OutLen = 0x00;             /* No char in the transmit buffer */
  OutPtrW = OutPtrR = OutBuffer;       /* Set pointer on the first item in the transmit buffer */
  /* UBG11: Divider_MSB=0 */
  setReg8(UBG11, 0x00U);                
  /* UBG21: Divider_LSB=0x60 */
  setReg8(UBG21, 0x60U);                
  HWEnDi();                            /* Enable/disable device according to status flags */
}


/* END VFDserial. */


/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale MCF series of microcontrollers.
**
** ###################################################################
*/
